AprilSylph/XKit-Rewritten

- dev/copy-libs.sh
- lib/spectrum.css
- lib/spectrum.js
- package-lock.json
- package.json
- src/browser/action.html
- src/browser/action.js
- src/scripts/_index.json
- src/scripts/painter.js
- src/scripts/painter.json
Make nice coloured edges at the top of your post to see quickly what kinda thing you're looking at.
> New script: Painter

- src/util/user-blogs.js
Helper functions that wrap around the `/v2/user/info` endpoint, giving easy access to the blogs the user has write access to.
> Add user blogs utility

- .github/FUNDING.yml
- src/browser_action/popup.html
My GitHub sponsor profile got approved, so I would like to have a button please 😄
> Add myself to FUNDING.yml

- src/scripts/anti_capitalism.js
- n/a
Refactors anti-capitalism to use #441.
Am I just doing this so that when it inevitably gets done at some point it doesn't merge conflict with other stuff I'm testing locally with this script? Maybe.
n/a
> Anti-Capitalism: use keyToCss

- src/scripts/show_originals.js
- n/a
This mimics the same refactors that other onNewPosts-based scripts got. Just roleplaying as April a bit.
n/a
> Show Originals: get posts from pageModifications

- src/scripts/show_originals.css
- src/scripts/show_originals.js
- src/scripts/show_originals.json
- Replaces the preference checkboxes specifying where Show Originals will run with an in-dashboard controls UI that allows the user to toggle the extension, where applicable. The user's selection is remembered. On blogs where the user's settings would show all posts anyway (those you have whitelisted; your own if you always show your own posts), the controls UI appears for consistency but is disabled.
The user's toggle selection is saved silently in local storage under a non-preference key similar to the Quick Reblog feature added in #450.
Rather than implementing complex conditional/on-click logic in the code that marks non-original posts, this simply marks non-original posts everywhere and toggles whether the extension is active by changing a data attribute on the timeline element and …
> Show Originals: New in-dash toggle UI 

- src/util/tumblr_helpers.js
- None!
Like the previous version of XKit, it'd be helpful for us on the Tumblr side to know when requests are coming from XKit. I think this should do the trick?
- None!
@AprilSylph hello
> Add XKit header to all API requests

- src/scripts/mirror_posts.js
- src/scripts/notificationblock.js
- src/scripts/postblock.js
- src/util/meatballs.js
To do: Write documentation.
```
- 
```
> Meatballs util: Fix functionality with React portals 

- src/scripts/collapsed_queue.js
- src/scripts/no_recommended/hide_recommended_posts.js
- src/scripts/seen_posts.js
- src/scripts/show_originals.js
- src/scripts/tag_tracking_plus.js
- src/scripts/tweaks/hide_my_posts.js
- src/util/react_props.js
- n/a
exposeTimelines is built into Tumblr now, and I didn't find any places where the built-in attribute differs from what we were setting!
resolves #565
> Remove exposeTimelines utility

- src/scripts/accesskit/visible_alt_text.js
- src/scripts/cleanfeed.js
- src/scripts/hide_avatars.js
- src/scripts/no_recommended/hide_radar.js
- src/scripts/no_recommended/hide_recommended_blogs.js
- src/scripts/scroll_to_bottom.js
- src/scripts/show_originals.js
- src/scripts/tag_tracking_plus.js
- src/util/language_data.js
- src/util/tumblr_helpers.js
- n/a
Converts the `translate` utility to be synchronous using top-level `await`.
n/a
> Convert translate utility to synchronous

- src/scripts/_index.json
- src/scripts/themed_posts.js
- src/scripts/themed_posts.json
This is definitely <https://www.tumblr.com/settings/labs>, I don't know what you're talking about.
Experimental script to color posts using the theme colors that are used in the blog cards.
||||
| - | - | - |
| ![image](https://user-images.githubusercontent.com/8336245/164793508-9353638e-ba77-482a-83a8-40f081cbfdd4.png) | ![image](https://user-images.githubusercontent.com/8336245/164793518-aef9f1c0-e5cd-4b9c-b5a6-89770256a1fc.png) | ![image](https://user-images.githubusercontent.com/8336245/164793520-711c02fb-b53f-4f0d-9161-7097f627f2b2.png) |
| ![image](https://user-images.githubusercontent.com/8336245/164793522-7d34c316-8058-496c-b162-2eee1c348560.png) | ![image](https://user-images.githubusercontent.com/8336245/164793523-42b25444-c119-4261-b68b-1f1d574b3ea7.png) | …
> new script: Themed posts

- src/scripts/tag_tracking_plus.js
- Prevents Tag Tracking+ new posts counts from stopping at two.
There are ad posts in the API response for /v2/hubs/[tag]/timeline.
It seemed like the simplest way to filter these out was simply to ensure that only posts tagged with the tag in question are counted, so I did that. 
Here are some unique keys from the house ad post object I looked at that are not contained in a regular post, in case a different method is needed/for future reference:
```json
"displayType": 1,
"sponsoredBadgeUrl": "https://www.tumblr.com/docs/en/relevantads",
"admMediaType": "tsp-display",
"adm": {},
"price": 0,
"adProviderId": "smart",
"adProviderPlacementId": null,
"adProviderForeignPlacementId": "1623962",
"adProviderInstanceId": "4bfcd452-5de3-4c3f-ba05-8d88d711f5fc",
"adRequestId": …
```
> Tag Tracking+: Remove ads/recommendations from api response

- src/scripts/tweaks.json
- Consistent grammar when referring to sticky effects.
> Tweaks: Minor grammar tweak

- src/scripts/tweaks/unsticky_tab_bar.js
- Fixes the unsticky tab bar tweak
resolves #707
> Tweaks: Fix unsticky tab bar tweak

- src/scripts/tweaks/show_all_tags.js
- it work again
typing with one hand is just as annoying as I thought it would be
resolves #787
> Tweaks: Fix show all tags

- src/scripts/trim_reblogs.json
¯\\\_(ツ)\_/¯ 
Tweaks the description of Trim Reblogs to hint that you use it after reblogging a thread or drafting a reblog of a thread.
Resolves #872.
> Trim Reblogs: More descriptive description

- src/util/tumblr_helpers.js
what am I even doing this is an embarrassment
> Fix `createEditRequestBody` helper

- src/scripts/trim_reblogs.json
Adds more related terms that will highlight Trim Reblogs in the extension pane search.
n/a
> Add more related terms to Trim Reblogs

- src/manifest.json
a release has not felt particularly warranted at any given time so far, but if you have a PR review coming up that feels like a reasonable point to do to or if you definitely don't and just want to do one somewhat at random, I wouldn't mind having the people who have been asking about xkit on android recently try out the quick reblog mobile patch (#893).
> bump version to 0.21.3

- src/content_scripts/meatballs.css
- src/util/meatballs.js
...oops.
This fixes a mistake I made and did not catch while testing #910: meatball menu item styles were not applied to the items added to blog menus.
> Meatballs util: Fix blog menu item styling

- src/manifest.json
> bump version to 0.21.11

- src/manifest.json
> bump version to 0.21.15

- src/util/interface.js
Prevents some console error spam when the user has the virtual scroller experiment.
Resolves #1203.
I didn't test this on its own.
> Interface Util: Prevent processing disconnected elements

- src/scripts/no_recommended.json
As per the linked issue, this changes the label on the No Recommended feature for posts to improve clarity.
Resolves #1210.
n/a
> No Recommended: Update post feature label

- src/scripts/tweaks/hide_follower_counts.js
- src/scripts/tweaks/no_focus_shadow.js
Were these scripts made before `keyToCss` existed? Possibly.
Confirm that follower counts are still hidden and the post focus shadow is still gone.
> Tweaks: Minor CSS refactors

- src/manifest.json
Drafts a release.
Feel completely free to ignore this! No idea if you have a plan in mind, here. (I know you mentioned 1.0 in passing somewhere).
Depending on the potential timeline, I think it _could_ make sense to start the timers early on getting #1276 distributed and on https://github.com/new-xkit/XKit/pull/2135 eventually being mergeable, separate from any new functionality if that's likely to happen soon. On the other hand, it very easily could not make sense!
n/a
> bump version to 0.23.5

- src/utils/inject/control_tags_input.js
- src/utils/inject/unbury_notification.js
- src/utils/react_props.js
https://github.com/AprilSylph/XKit-Rewritten/pull/1466#discussion_r1616421880
(q: would I rather just commit to the dev branch? a: not necessarily; I don't much enjoy getting merge conflicts on a branch while actively working on it because someone else committed to it while I was, though it's not like this has happened to me more than like once. let me know what you prefer.)
> MV3 branch: migrate missed utils to path-based `inject()`

- docs/Chapter 2 - Getting started.md
Mentions `npm start` in the extension documentation, including how to target different Firefox versions or Chrome.
> Documentation: Document `npm start`

- src/utils/timeline_id.js
Adds the drafts timeline ID to the timeline ID util.
> Timeline id util: Process drafts timeline

- src/content_scripts/main.js
- src/features/accesskit.js
- src/features/no_recommended.js
- src/features/tweaks.js
Automatically labels (most) style elements with a data attribute indicating what feature they're associated with, helping with troubleshooting.
> Label style elements in dev tools

- src/features/trim_reblogs.js
>  Trim Reblogs: Fix gap in control buttons after trimming

- src/features/mass_privater.js
As per the linked issue, this applies some query parameters to the Mass Privater post collection API endpoints that I don't know how I (we? I?) missed, improving fetch efficiency and speed.
Resolves #1595.
> Mass Privater: Improve fetch efficiency

- src/manifest.json
Drafts a release.
(Reasonable opinions can differ, but I kind of think this is worth one.)
> bump version to 1.0.3

- src/features/quick_tags.css
- Make a post with a tag.
- Load the extension without this PR. Use Quick Tags to add a tag to the post. Confirm that the footer shifts vertically slightly when the tag is applied.
- Refresh. Load the extension with this PR. Use Quick Tags to add a tag to the post. Confirm that there is no unexpected visual effect when the tag is applied.
> Quick Tags: Update post-edit footer style

- src/utils/timeline_id.js
Adds a timeline filter function for the "for you" timeline.
The legacy data-timeline attribute is not tested (I assume I'd have to force feature flags to do so and I can't be bothered to check it that's actually possible); I previously collected this information and committed it in #1485.
> Timeline util: Add filter for "For You"

- eslint.config.js
Fixes a comment typo that I didn't catch in review.
Aside: I did give https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker a try and it's pretty nice. Didn't find anything else.
n/a
> chore: Spelling fix

- docs/Chapter 4.0 - Feature framework.md
- docs/Chapter 4.1 - Feature metadata.md
- docs/Chapter 4.2 - Feature modules.md
Updates some outdated references to "scripts" in various documentation files.
Feel free to point this at master or at #1828. 
n/a
> docs: update some "script" references to "feature"

- src/action/popup.html
Reverts 1f547d49fc4f75c6e8af665039e705391a037652.
Sadly, it looks like linking to the Sponsor window from the contributors graph no longer works. I thought about just duplicating the links created by `FUNDING.yml` here instead, but I think I still prefer linking to the repository's Sponsor window, since we can update that without pushing out a new addon version.
Before | After
-|-
This is quite a few months overdue if considering when I re-enabled the Sponsor button in this repository... but I was wrestling the question on whether or not I _deserve_ to advertise it, given the level of my open-source work output in those months (and the many months prior). The answer I ultimately arrived at is that it's a silly question to begin with; I will become more motivated to do open-source work as …
> chore: restore "Donate" links section in control panel

- src/manifest.json
Aw, I guess I don't have privs to do this. Oops.
> chore: bump version to 1.0.17
