AprilSylph/XKit-Rewritten

docs/framework.md

I *think* this is all it needs in terms of documentation, but then again I implemented the thing, so it may not be as obvious to outsiders.

Re-add documentation on the color preference type

---

src/scripts/timestamps.js

This avoids the timestamps bug when posts don't have reblogs by not doing anything when posts don't have reblogs.

Fix timestamps undefined but slightly better

---

src/scripts/cleanfeed.js
src/scripts/timestamps.js
src/util/react_props.js

This lets extensions that don't need updated-up-to-the-moment react props save on a few function calls. Pretty insignificant now, but might be nice when other interface functions start needing react props.

Cache react props

---

src/scripts/painter.js
src/scripts/painter.json

- Users may now select a colour for highlighting user-input tags using the Painter extension.
- There is also a functionality for highlighting tags from the source post, in a similar way to how Tumblr's tag filtering works.
If the tag colour is set, the script loops through every tag on the post to see if any in the textarea match it, and applies the colour to the post if so. If this initial search doesn't get a result, and the checkbox for searching the source post is ticked, it will fetch the source post and look through its tags in a similar way, colouring the post if a match is found.
None.

[Painter] Add tag highlighting

---

src/browser_action/render_scripts.js

- None
All preference writes are debounced by half a second, which means that changing preferences (especially of `text` and `textarea` types) will no longer create restart spam among preferences.
None.

Debounce preference input

---

src/browser_action/configuration.css

- Use the blue highlight color on the focused script preference title element, rather than on any open script preference title element. I think this is less visually confusing and makes tab navigation more clear.
- Make the grey highlight on hover only active when the title element is hovered, not when the dropdown contents are hovered. (Not sure if this is better or not? It feels a bit more natural to me. Revert 1f5b422 to see the difference.) 
The blue highlight css has priority over the grey highlight css (only) because it comes second.
n/a

Popup: use background color to indicate browser focus

---

src/browser_action/render_scripts.js

- When the popup is opened to the default "configuration" tab, all scripts pop in at once rather than one at a time. This is quite a bit faster in Chrome and Edge (tested on MacOS), which re-render the popup at a different height each time a script is added in a fairly janky animated process, but - rather annoyingly - a bit slower in Firefox (though the animation is still cleaner).
- `scriptTemplateClone`s are appended synchronously after all are generated. Preferences are still asynchronous, which is fine since they don't affect the popup size.
- If you wanted to, you could probably get rid of some of the ~8 frame delay on Firefox by rendering them all as blank and fetching the JSON asynchronously afterward? but yeah it's 8 frames
- n/a
(Fun aside: apparently if you open and close a …

Render scripts synchronously

---

src/scripts/shorten_posts.css

- Shorten posts doesn't break sticky avatars in Chrome
- Goes back to (only using) `overflow-y: clip`, which now that [https://github.com/AprilSylph/XKit-Rewritten/commit/f6ffb57776c129d611327328af70e8211bb8a611](https://github.com/AprilSylph/XKit-Rewritten/commit/f6ffb57776c129d611327328af70e8211bb8a611) is implemented, seems to work on both browsers.

 Shorten Posts: fix avatars in Chrome, part 3

---

src/scripts/accesskit.css
src/scripts/accesskit.json
src/scripts/accesskit/visible_alt_text.js

Adds an option to AccessKit that displays any (non-default) image alt text in posts as a caption below the image.
It checks for any not-yet-processed imageBlocks in onPostsMutated (skipping blocks where the image hasn't loaded yet); if the alt text isn't the default "Image" text, it inserts a caption into the block (I used figcaption since imageBlock is a figure, but div would probably work too)
Like I mentioned in #192, the styling probably needs some work, haha. I also haven't spent much time testing in Chrome yet, though a quick check in tumblr.com/search/alt+text seemed OK.
closes #192

[AccessKit] New script: display alt text below images

---

src/scripts/no_recommended/hide_recommended_blogs.js

Extends No Recommended's "Hide recommended blogs in the sidebar" setting to also hide the sidebar blogs widget on /tagged pages (XKit 7 currently does this with the Tweaks > Sidebar > Hide Recommended blogs option).
Checking for the widget is a little different on tag pages than on the dashboard (the label includes the tag name so checking it requires a regex, and I also used a cssmap class selector to avoid something like `aside > div > div > div > div`). I was torn between trying to merge the two blocks in checkForRecommendedBlogs together vs. duplicating some code to try and keep the code more straightforward(?); went with the latter, but could definitely change that if needed.
Was also wondering about renaming recommendedBlogsLabel and recommendedBlogsPattern to something that …

No Recommended: Hide blogs in sidebar on tag pages

---

src/util/react_props.js

- Fixes seen posts, show originals, and the hide my posts tweak.
`exposeTimelines`'s css selector used to be created from only the first entry in the CSS map for `timeline`. Tumblr was, at the time of this writing, using the second entry, so this selector would fail.
Normally this would be more obvious, as one would usually call `keyToClasses` and the plural function name is a good hint that there can be more than one class, but as this code is in an `inject()` call it cannot use other utility functions.
resolves #210

exposeTimelines util: handle >1 CSS class

---

src/scripts/quick_reblog.js
src/scripts/quick_reblog.json

- Remembers the last selected blog in the Quick Reblogs popup. The selection persists across navigation in the React page, but not across full page reloads - I admittedly haven't looked much into how saving user data in XKit works yet, but I'd be down to look into storing the selection more persistently if anyone thinks it'd be a good idea.
(Edit: the more I think about this, the more I think it probably should persist across reloads if possible, so I'll keep this as a draft until I've looked into that more - open to any feedback in the meantime though!)
- Probably worth noting that the event listener on blogSelector sticks around when this option is disabled and could theoretically get attached multiple times if you toggle the setting a lot (doesn't affect behavior, though) - I doubt …

Quick Reblog: Remember last selected blog

---

src/scripts/notificationblock.js
src/util/react_props.js

- None (slight potential for reducing flicker along with other changes; insignificant performance gain)
This adjusts a pattern that gets used twice in the codebase: once in the exposeTimelines util, and once in NotificationBlock's custom inject callback.
Right now, both callbacks always inject a function that get the CSS map and use a querySelectorAll to see if they actually have to do anything. Most of the time, though, these functions should do nothing (new timelines are infrequent; most of the time mutations are not new notification drawer elements).
This:
- Generates the CSS selector outside of the inject call. (This isn't a performance gain - tumblr.getCssMap is ~free - but it's nice, and an excuse to use the previously-unused ability to give an injected function arguments.)
- Skips …

Refactor exposeTimelines and NotificationBlock's injected code

---

.eslintrc.json

- None
This enables eslint-plugin-import's recommended options. This includes import/no-unresolved, which will check for import paths that are mistyped.
Apparently the Standard JS ESLint config doesn't enable this rule, despite including the plugin. Not sure why, but I could imagine a reason.
n/a

ESLint: Lint for incorrect import paths

---

src/scripts/no_recommended/hide_blog_carousels.js

- Dashboard should generally perform better if the "hide blog carousels" option is enabled
This slightly changes the way No Recommended's option to hide blog carousels works. The current CSS causes Tumblr's code to get a bit confused: the recommended blogs carousel has infinite scrolling, and certain CSS manipulations confuse its "distance to the right edge" calculation into loading new posts in the background constantly. This fixes this behavior, which reduces the total amount of content loaded on the dash by about half.
(image shows results of loading page with fix, then reverting fix and waiting for about a minute)
- n/a

No Recommended: CSS optimization

---

src/scripts/show_originals.css
src/scripts/show_originals.js

In rare cases with large displays, Show Originals could result in a user's timeline rendering as short enough vertically that it fits in the browser viewport, resulting in nowhere to scroll to trigger infinite scrolling. This ensures this does not happen.
The timeline is set to a minimum height of 100vh, or 100% of the browser viewport height, if it does not contain pagination controls. It is not right at the top of the page, so this always results in the page height being at least a bit taller than the viewport.
Duplicating `/v2/timeline/dashboard` as both string and regex doesn't feel very DRY. `getPostElements` could be overloaded to take a string for its `timeline` prop but I remember you preferring to avoid `typeof`.
None, but discussed in discussion #107

Show Originals: Ensure user can scroll

---

src/scripts/timeformat.js
src/util/mutations.js

- TimeFormat no longer waits for the page to stop mutating before formatting Tumblr's timestamps. This eliminates the brief time where Tumblr's unformatted timestamps are visible, but may make post rendering technically slower. Overall, this is visually interpretable as a performance improvement.
Adds a new export, `pageModifications`, to `util/mutations.js`. This new object exposes two functions:
- `register(selector, modifierFunction)`: Adds the callback to the listener list and associates the selector with it, then runs the callback, passing all matching elements on the page as an Array argument.
- `unregister(modifierFunction)`: Removes the callback from the listener list.
Once a modifier function is registered, the ever-active MutationObserver will compile an array of every mutation …

add pageModifications engine

---

src/util/notifications.js

I don't know that I would actually make this change! It is a bit silly, but it works.
Plus: Completely insignificant performance gain (<1ms) when Tumblr does any DOM mutations.
Minus: Changing to/from mobile view/peepr while a notification popup is active does not transfer the notification popup to the new UI. Anyone who finds the toast container with dev tools when it's not in the right place will be confused.
This defers moving the toast container to the right place until it actually gets used to display a notification.
n/a

Notifications framework: tiny optimization

---

src/scripts/shorten_posts.json

- Adds larger 4x viewport height multiplier to the Shorten Posts script options.
For me, the viewport height options for Shorten Posts are too small for my liking. I mostly want to limit posts with annoyingly lengthy discussions or any of the infamously long posts floating around, but the current highest 2x option ends up limiting like, most GIF-set posts for example. 4x seems to cover that use, after testing a bit.
I was originally going to add an input field for a custom multiplier instead, but I couldn't think of a concise way to explain how to use it. I think that may be why you went with a dropdown here?
None.

Shorten Posts: add 4x viewport height multiplier option

---

src/scripts/quick_reblog.js

- n/a
This fixes a console error when alreadyReblogged tries to process the reblog link on posts that don't have one, like when viewing the drafts page.
n/a

Quick Reblog: Fix console error on drafts page

---

src/scripts/scroll_to_bottom.js

- Scroll to Bottom is 20-25% faster.
- Scroll to Bottom's knightRiderLoader check is 100-150x faster.
Sounds cooler that way, but meh. Amdahl's law strikes again.
(`knightRiderLoader` is currently one css class; `descendantSelector('main', 'loader', 'knightRiderLoader')` is currently about 250 rules, so even though CSS selectors are evaluated right to left there's a lot of duplicate work going on if the full selector is fed to QSA. Certainly not the most elegant looking PR diff, I have to admit, but I didn't think of a way to do this in fewer lines.)
n/a

Scroll to Bottom: Query performance optimization

---

src/scripts/accesskit/disable_gifs.js

- n/a
This fixes a console error when Disable Gifs' asynchronous `onload` callback fires after the gifElement has been unmounted from the page by Tumblr's placeholder code.
There appears to be no functionality problem because of this or functionality change due to the fix, that I can tell; `processGifs` gets fired again when the image is re-mounted.
n/a

Disable Gifs: Fix console error

---

src/scripts/tweaks.json
src/scripts/tweaks/hide_note_count_types.js

- Adds a tweak to hide the colorful note count type indicators next to the note count on posts.
Are you supposed to add a co-author credit to your merge commit if 99% of your PR is copy-pasted? It seems polite, right? :D
Anyways, I've been running `.📝noteCountTypes { display: none !important; }` in Stylus with my translation script pretty much ever since I got this a/b test.
n/a

Add tweak to hide note count type indicators

---

src/scripts/scroll_to_bottom.js

- Scroll to Bottom is 0.02% slower. I think it'll survive.
This reverts the performance-optimization-at-the-expense-of-clean-code of #431, as the (single) selector created by the new resolveExpressions function makes it unnecessary. (I haven't done what I would consider exhaustive tests of `:is()` performance yet, but the original 4-level cartesian took 500ms, the 3-level cartesian took 130ms, and both the single selector in #431 and the new singly nested :is() take less than 1.5ms, so... yeah.)
n/a

Revert "Scroll to Bottom: Query performance optimization (#431)"

---

src/scripts/accesskit/no_user_fonts.js
src/util/css_map.js

- n/a
This modifies the keyToClasses/keyToCss utilities to optionally accept multiple keys as multiple arguments, any of which their output classes/output selector will match. This is useful for things like the no user fonts accesskit script and anti-capitalism.
This also applies the change to no user fonts.
Honestly, though, use cases for this are incredibly rare, so I could see the argument that it's not really worth it.
n/a

CSS utilities: Accept multiple keys

---

src/scripts/quick_reblog.js

Honestly, I'm not sure if this was something you wanted to work on yourself, and if so, I am 100% fine with that! I just wanted to learn about the crypto functions available in javascript and the way XKit Rewritten interfaces with storage... and then wound up learning about attaching event listeners and how to convert an ArrayBuffer to base64.*
*hope you're in Node; if not, reject all of the solutions as awful and do something entirely different.
Pretty sure there are ways to do this in less code. (Honestly, if you want to use any of this, feel free to copy-paste/I could make it a branch in this repo if you want.)
- Quick reblog's "remember the last selected blog in the popup" option persists through page reloads, yet the local storage contains no record of who the user is.
Instead of …

Quick reblog: Save last selected blog in local storage

---

src/scripts/tweaks/footer_unredesign.js

- Fixes a 12px gap at the bottom of posts that was not there before the new notes UI.
Two things contribute to the spacing at the bottom of posts: a 12px postActivityWrapper margin and a 12px footer padding. Opening the new notes view puts it between these.
Tumblr's code does this... I think:
> No redesign, closed (gap is too big; we only want one of these): 
> postActivityWrapper yes
> footer yes
> 
> No redesign, open (bottom of footer looks slightly weird, so we want no footer):  
> postActivityWrapper yes
> footer yes
> 
> Redesign, closed:
> postActivityWrapper yes
> footer yes
> 
> Redesign, open:
> postActivityWrapper no (overridden)
> footer no (overridden)
I am fairly certain that according to this, a) the correct fix for this behavior is "remove the footer padding when removing …

Footer redesign revert tweak: Fix gap at bottom of posts

---

src/scripts/tweaks/footer_unredesign.js

Fixes a visual issue where the tip indicator was misplaced on posts without any notes. (Also fixes a minor vertical positioning oddity regardless of whether there are notes or not.)
CSS for two positioning option variants is supplied, one commented. I don't think I have a preference.
| Before |
| --- |
| <img width="597" src="https://user-images.githubusercontent.com/8336245/153539963-90d483eb-f7a8-4a6b-ab70-df33b077d544.png"> |
| After (left align) |
| --- |
| <img width="597" src="https://user-images.githubusercontent.com/8336245/153539955-889a17c6-f165-4a49-ab92-0e52217794f8.png"> |
| After (right align; code is commented) |
| --- |
| <img width="597" src="https://user-images.githubusercontent.com/8336245/153539961-24730b6c-c632-4563-aeed-391c8d332a47.png"> |
Something something …

Post footer redesign tweak: Further improve tip button position

---

src/scripts/tweaks/footer_unredesign.js

Improves the behavior of the post footer redesign tweak if there are a large number of icons.
| Before |
| --- |
| <img width="668" src="https://user-images.githubusercontent.com/8336245/153604000-e45200fa-bc20-487a-9d91-45fd2d5fff9b.png"> |
| After |
| --- |
| <img width="668" src="https://user-images.githubusercontent.com/8336245/153603996-064dd4c8-0c8b-4bdb-9700-44e5cf2ce30b.png"> |
I was hoping there would be some magic keyword like `justify-self` for this, but I guess it doesn't work in flexbox (kinda reasonable).
Resolves #435.

Post footer redesign tweak: Improve overflow behavior

---

src/scripts/accesskit.css

Improves alt text captions wrapping on very small images.
Before:
After:
`min-content` sets the minimum width to the width of the longest word. This is not perfect:
If you know of a way to improve this, that would be awesome. Perhaps just setting the minimum width to a reasonable quantity is better? But that doesn't adapt nicely to single word captions, so I dunno.
Edit: Oh, yeah, and I have no idea what the idiomatic css rule order is supposed to be.
n/a

Visible Alt Text Tweak: Improve wrapping on tiny images

---

src/util/mutations.js

- Fixes buggy behavior when clicking to navigate while posts are loading
This filters elements out of pageModifications if they aren't mounted to the DOM, i.e. if they were added and then removed before onBeforeRepaint fires. This includes a bunch of <img> elements while scrolling, some loading indicators, a few random things, and notably the entire post list if you click to navigate twice in a row while Tumblr's javascript is still loading your first navigation action. This should remove some unnecessary processing done by extensions like AccessKit Visible Alt Text.
I looked through the list of listeners registered to pageModifications and I don't see anything this would obviously break.
Discussion #479 (fixed in practice, though that should probably have another fallback just in case of …

Fix pageModifications processing unmounted elements

---

src/scripts/quick_tags.js

Yep, it's just 66cb198 applied to quick reblog.
- prevents unintentionally triggering Tumblr's weird handling of quotes in the tags field
I do wish there was a clean way to integrate this into the post form, but it obviously makes no sense to add a quick tags text input to a form that already has a text input for tags, and silently editing the tags would make sense as a standalone extension or tweak, maybe, but would be a weird side effect of quick tags itself.
If this were really common, it could be a separate fix-my-quotes-please post form button (perhaps one that only showed up if you had quote characters in your tags), but eh.
n/a
#489 again

Quick Tags: replace quotes in tags input

---

src/util/mega_editor.js

- n/a
This adds the async keyword to the mega-edit utility so that it uses the asynchronous return path in the new inject() function.
I... admittedly PR'd this without testing it since I didn't save my test code for the mega edit utility as far as I can tell. Whoops. Might get to it later, though.
n/a

Fix mega edit utility with new inject() function

---

src/browser_action/resize_frames.js
src/scripts/postblock/options/index.css
src/scripts/quick_tags/options/index.css

- iframe preferences no longer sometimes capture user scroll
~~I thiiiiink this is the correct fix. Probably. Maybe? Well, it seems to work.~~
~~This adds one to the height set on iframe preference elements by the resize frames script, ensuring that even if the actual height of the document is fractional and `document.documentElement.scrollHeight` rounds down, all of the content will still fit in the iframe without a scroll bar appearing.~~
~~Not sure if this is better than changing the overflow css property, assuming that that also works.~~
This changes the overflow CSS property, which does work! It must be changed on the iframe contents, though, not the iframe itself.
Resolves #509

Popup: Fix iframe options sometimes capturing scroll

---

src/browser_action/popup.js
src/browser_action/render_scripts.js
src/scripts/accesskit.json
src/scripts/anti_capitalism.json
src/scripts/cleanfeed.json
src/scripts/collapsed_queue.json
src/scripts/mass_unliker.json
src/scripts/notificationblock.json
src/scripts/quick_reblog.json
src/scripts/quick_tags.json
src/scripts/seen_posts.json
src/scripts/trim_reblogs.json
src/scripts/tweaks.json
src/scripts/vanilla_audio.json
src/scripts/vanilla_video.json

- Searching the popup for terms related to a script like the name of its XKit 7 equivalent will still find the script.
Probably should have proposed this a year ago when more people might have been switching from XKit 7. Then again, someday it will stop working, so maybe there will be another wave then.
Uses a data attribute on the script element.
Would require an update to the manifest documentation.
Discussion #113

Popup: Add additional searchable text to scripts

---

src/scripts/mutual_checker.js

- n/a
This is a minor refactor of the reprocessing logic in mutual checker which ensures that when you click to unfilter a post, it is processed again. Rather than querying the entire page for these posts, this just checks the new posts.
I initially kept the "remove excludeClass if necessary" logic:
```js
filterPostElements(postElements, { includeFiltered: true }).forEach(postElement => {
if (postElement.classList.contains(mutualsClass) && postElement.querySelector(`.${mutualIconClass}`) === null) {
postElement.classList.remove(excludeClass);
}
});
```
which works just as well as the committed code, which replaces the built-in exposeTimelines logic with one with an exception.
This PR is entirely a matter of which you think is more clear. The performance benefit is not significant and the …

Mutual Checker: Minor refactor of reprocessing

---

docs/Chapter 4.0 - Feature framework.md
docs/Chapter 4.1 - Feature manifests.md

I am not good at documentation prose :D
This adds documentation about the relatedTerms manifest key added in #506.
It also adds an example help link to the example script manifest (it's a dead link, but still. Seemed clearer than linking to the location of the document in question, or something).

docs: document related terms manifest key

---

src/scripts/cleanfeed.js
src/scripts/mirror_posts.js
src/scripts/mutual_checker.js
src/scripts/no_recommended/hide_recommended_posts.js
src/scripts/notificationblock.js
src/scripts/painter.js
src/scripts/postblock.js
src/scripts/quick_reblog.js
src/scripts/quick_tags.js
src/scripts/show_originals.js
src/scripts/tag_tracking_plus.js
src/scripts/timestamps.js
src/scripts/trim_reblogs.js
src/scripts/tweaks/hide_my_posts.js
src/util/inject.js
src/util/react_props.js

- Slightly increased performance when loading new posts
As we discussed in #416, it should be possible to skip using querySelector in some (all, I think, but at the expense of too much complexity in some cases) injected functions by injecting script elements into relevant DOM containers. I got worried it wouldn't work, so I tried it, and it seems to! 
This implements a parameter in `inject()` specifying which DOM element the script will be injected into. Because the script can find its location via `document.currentScript`, this removes the need for injected functions to communicate which element they are supposed to query or affect via serializable data and thus the need to use querySelector/querySelectorAll in the page context to find an element when the extension context already knows …

TimelineObject utility: Process elements directly

---

src/scripts/scroll_to_bottom.js

- n/a
This uses a CSS selector in Scroll to Bottom's clean function instead of a variable reference. This ensures that clean removes buttons added by a stale version of XKit that has been invalidated by an update or developer refresh in Firefox.
n/a

Scroll to Bottom: remove closure from clean()

---

src/scripts/accesskit.css
src/scripts/accesskit/visible_alt_text.js

- AccessKit's alt text captions no longer act like part of the button that opens the lightbox, but instead act like regular text boxes that can be selected and copied.
Not tested on mobile.
I was surprised at how easy this was, though it does feel a little weird. But I guess the state of "being inside a button element" confers a set of attributes that are ultimately all manipulatable.
Discussion #519

AccessKit: Make alt text user-selectable

---

src/scripts/accesskit.css
src/scripts/accesskit/visible_alt_text.js

- AccessKit's alt text captions can now be selected in the radar in the same way that they can be in posts in other locations.
I had actually originally assumed `preventDefault()` would be necessary in #520, but it worked without it, so I committed it that way, thinking, "wow, button elements are weird." Well... turns out that it is necessary!
n/a

AccessKit: Make alt text user-selectable in the radar

---

src/scripts/accesskit.css
src/scripts/accesskit/disable_gifs.js
src/scripts/cleanfeed.css

...by not using z-indexes at all. Certainly not the only way to solve this.
- AccessKit paused gifs and CleanFeed hidden images no longer appear over Tumblr's native shorten post control element and flicker when hovered.
Rather than adding a z-index to the Tumblr native shorten post control element, this removes the z-indexes from the Disable Gifs elements and the CleanFeed element and uses DOM ordering to ensure that they appear on top of the images they are supposed to replace.
Cleanfeed's element is an `::after` element, so I don't think it's possible for it to be out of order(?) and its z-index seems unnecessary.
Disable Gifs, as you pointed out in the relevant GitHub issue, needs to handle gifs being removed from the DOM and reattached as the last child of their containers, since …

Fix z-index thrashing with native shorten posts

---

src/scripts/show_originals.css
src/scripts/show_originals.js

Because navigating within the blog view to another blog (whether it is to a single post or to that blog's timeline) does not unmount the timeline element, the Show Originals controls are not removed or changed to reflect the new location. Using the existence of the controls element as part of a state machine, which I previously did, was evidently a bad idea.
Fixes UI desync bugs in the Show Originals UI when soft navigating within the blog view modal:
- navigating from a whitelisted blog to a non-whitelisted blog does not switch from whitelist to non-whitelist and vice versa
- navigating from a timeline where reblogs are hidden to a single post which is a reblog hides the single post
This state machine was getting pretty complicated and unwieldy, and I want to minimize complication in a …

Show Originals: Fix UI desync in blog view

---

src/scripts/tweaks/footer_unredesign.js

I haven't done what I think of as a  "self-review" of this yet, per se. Seems to work though.
- Fixes the footer redesign revert tweak not working after Staff removed the old footer CSS.
Primarily based on the comment in #413. This removes the manipulation of the `footerRedesign` class, which no longer exists, implementing the old footer css explicitly.
Staff added a `footerRow` element in between the footer element and its children, necessitating a few tweaks.
The functionality on #459 is done how I personally think is the most clear: always putting a bottom ~~margin~~ *padding* on the footer; never putting a top margin on the `postActivityWrapper`.
#553

Footer redesign revert tweak: New implementation

---

src/scripts/accesskit/disable_animations.js

- Removes the animated fire behind the Blaze menu when AccessKit's Disable Animations option is on.
I suppose one could possibly freeze this instead of removing it if there's a way to copy the contents of a canvas?
n/a
n/a

AccessKit: Remove blaze fire animation with disable animations feature

---

src/scripts/accesskit/visible_alt_text.js

This is one way of solving #557. Perhaps not the best way; it would be convenient to be able to preview the alt text that you have written for an image while composing it. Getting the styling correct seems nontrivial without a better understanding of the Gutenberg code than I currently have, however.
- There is no visible alt text in the post compose form, but at least it isn't buggy and doesn't change formatting suddenly without user interaction.
n/a
#557

AccessKit: : Disable visible alt text in Gutenberg editor

---

src/scripts/shorten_posts.js
src/scripts/show_originals.js
src/util/interface.js

Question: Do we want to rename this option flag to `noBlogView`? Edit: Done!
- Shorten posts is consistently inactive in the blog view.
The noPeepr flag now checks for the blog-theme-specific styles that are applied to the view formerly know as Peepr in both glass and non-glass modes.
Checking for a parent with a style attribute is a bit faster than calling `getComputedStyle`.
Resolves #569

Update "blog view" exclusion filtering

---

src/scripts/seen_posts.css

~~I think this works. Ran out of posts to test on at the moment.~~
- Seen posts consistently dims blazed posts.
Sets the opacity on the entire listTimelineObject instead of just the article element. I can't think of a place where this would be a problem, but I could be wrong?
Resolves #559.

Seen Posts: Fix dimming blazed posts

---

src/scripts/tweaks.json
src/scripts/tweaks/show_all_tags.js

Feel free to close this; it was already kind of rejected with a batch of XK7 tweaks, IIRC, but I don't think I actually put it in the list for some reason.
- Adds a tweaks option to show all post tags instead of requiring you to click a button.
n/a
n/a

Add show all tags tweak

---

src/scripts/accesskit.css
src/scripts/accesskit/disable_gifs.js

- XKit 7's disable gifs and XKit Rewritten's disable gifs no longer cause styling issues when both enabled.
n/a
resolves #550

AccessKit: Fix XKit 7 disable gifs incompatibility

---

.eslintrc.json

- n/a
I don't think this is particularly important, but fun fact: the eslint `plugin:import/recommended` preset doesn't include `import/no-cycle` and so circular dependencies currently aren't linted. I don't really expect this extension to run into this, but it could plausibly happen between util files.
n/a

Enable import/no-cycle lint rule

---

src/scripts/mutual_checker.css
src/scripts/mutual_checker.js
src/scripts/mutual_checker.json

- Added option to Mutual Checker script to only show posts by mutuals on dashboard.
- Hides via CSS all the posts made by non-mutual blogs.
Issue #588

Implementing option to only show posts from mutuals requested in #588

---

src/scripts/tweaks.json
src/scripts/tweaks/hide_liked_posts.js

Adds a tweak to hide liked posts on the dashboard.
Two functionality considerations:
- As per my comment in the linked issue, should this only check posts on load or should it immediately hide a post when you press the like button? (Currently implemented the former.)
- Should this exclude your own posts? Tweaks can't really have sub-preferences. I personally assume that, by default, no script hides my own posts besides the one whose function is specifically "hide my own posts," but I can definitely imagine disagreement on this.
n/a
resolves #594

new tweak: Hide liked posts

---

src/util/css_map.js

- Fixes script misbehavior when Tumblr removes CSS keys
If `keyToCss` is called with an invalid/no-longer-valid key name, it now outputs `:is()`, which doesn't appear to match anything. Previously, it cast `undefined` to `'undefined'`, and thus output `:is(.undefined)`, which actually did match a `postAttribution` element briefly rendered inside asks as they load that had the css class `undefined`.
Addresses the core issue in #602

Fix CSS map removed key behavior

---

src/scripts/tweaks.json
src/scripts/tweaks/hide_footer_tooltips.js

No idea if this works with the newest footer redesign, as I don't have it.
- Adds a tweak to hide the tooltips for the post footer control buttons.
This could also target `article footer ${keyToCss('controlIcon')} ${keyToCss('popoverHolder')}`; not sure which is more robust against changes. `popoverHolder` is used for footer popovers that we don't want to target (the "oldest first" / "newest first" selector), so care must be taken here.
resolves #595, #575

new tweak: Hide footer tooltips

---

src/scripts/accesskit.css
src/scripts/accesskit/disable_gifs.js

Well, this is kind of a mess (a least temporarily?)
It appears that Tumblr now places a "poster" static image element over GIFs, with CSS that defaults both the "poster" and actual animated image element to `visibility: hidden`, and moves a class that sets `visibility: visible` from the poster to the animated element once the gif loads.
If this is fully rolled out, usable everywhere, and we want to rely on it, this makes the feature extremely easy to implement, as we can just reuse the "poster" element instead of using canvases. I lack the forbidden knowledge to know if this is currently true.
In the meantime (?), as a quick and dirty fix, this PR stops a second canvas element from being created by the "poster" element and ensures that whether or not the `visible` class gets copied, the …

Fix disable gifs "poster" incompatibility

---

src/scripts/no_recommended/hide_blog_carousels.js

- Fixes GIFs from carousels sometimes appearing in the background between posts on accounts with Tumblr's latest changes to GIF loading.
Tumblr's changes to GIF loading (detailed in #615) toggle the `visibility` css attribute on image elements to switch between static and an animated versions of GIFs.
This interferes with the changes in #282, as the Tumblr-set `visibility: visible` on GIFs within carousels overrides the `visibility: hidden` used to hide the carousels.
This ensures that these image elements have `visibility: hidden` set. This could instead be `.${hiddenClass} > div * { visibility: hidden; }` if concerned about other carousel elements having their visibility set (not sure of the performance impact).
This is the kind of thing I think I would probably want commented?
resolves …

No Recommended: Fix GIFs in hidden carousels appearing

---

src/scripts/no_recommended/hide_blog_carousels.js

Okay, so, listen. Listen here. I, uh, I was just testing you, before.
- Fixes GIFs from carousels sometimes appearing in the background between posts on accounts with Tumblr's latest changes to GIF loading... again, if you have AccessKit's Disable GIFs enabled.
#618 fixes the GIF elements themselves, but not the canvas elements that Disable GIFs creates, something that definitely occurred to me last time and which I didn't fix just to make things interesting.
n/a, I didn't write the issue

No Recommended: Fix AccessKit disabled GIFs in hidden carousels appearing

---

src/scripts/accesskit.css

Oh, I guess it's "pause GIFs" now, huh.
- Fixes animated GIFs being visible through the paused GIF overlay if the image in question has transparency.
resolves #617

AccessKit: Fix paused transparent GIFs

---

src/scripts/no_recommended/hide_tag_carousels.js

- Extremely minor (basically irrelevant) performance increase when "hide tag carousels" is enabled.
This applies the changes in #282 (and the subsequent tweaks) to the hide tag carousels script. Tumblr loads far fewer recommended tags than recommended blogs before giving up (it seems like the tag list is quite short, while apparently there's a nigh-unlimited supply of recommended blogs and it might actually be some kind of timeout in that case). But, you know, why not.
n/a

No Recommended: Apply blog carousel CSS to tag carousels

---

src/scripts/quick_reblog.js
src/scripts/quick_tags.js

- Typing a >140 character tag into the quick tags popup text box displays an error message and prevents submission.
Non-regex version. The regex version (setting a `pattern` attribute on the input element) requires designing some CSS to indicate the invalid state, and I didn't come up with anything that didn't look terrible. It's much fewer LOC though.
resolves #584

Quick Tags/Quick Reblog: Validate tag length

---

src/scripts/notificationblock.js

- NotificationBlock menu items appear on non-editable posts
The notificationblock menu item appears on any post from any of the user's blogs, regardless of whether the user has edit access to that post.
This makes sense for blazed posts the user has made, as well as group blog posts that the user didn't make and can't edit, as the user can still see notifications on those.
resolves #627
(for real this time)

NotificationBlock: Fix menu item missing on non-editable posts

---

src/scripts/accesskit.css
src/scripts/accesskit/disable_gifs.js

- Disables GIFs in more places: the related tags previews and the banners above the timeline.
The `tagImage` element is quite similar to an image in a post, just smaller and without a `figure` element surrounding it. Of course, the gif labels are rather intrusive in this case - maybe they could be smaller? - but I assume a user who wants this script would prefer this to these elements being animated (well, I do, anyway). The `takeoverBanner` element is also very similar.
The communityHeaderImage element is harder: it has a gif set as its background image and the text overlay is contained within it. Rather than doing some really complicated DOM manipulation to pause it, I just used the method from the boring tag chiclets script to remove its background. Not ideal, but it works.
n/a
--- …

AccessKit: Disable more gifs

---

src/scripts/accesskit.css
src/scripts/accesskit/disable_gifs.js

I am kind of surprised React is okay with this. Anyway, I wanted to see if it worked and if the resulting functionality felt enjoyable and natural.
- Hovering over any paused gif in an imageblock unpauses the entire image block
~~Branch based off of #552; presumably I'll force push rebase this when it gets merged and if this is something we want to pursue.~~
This adds a wrapper div element around entire photosets and hides the paused gif overlay if the wrapper is hovered.
Not yet implemented: only performing this manipulation on gifs (cannot be synchronous; would have to be in processGifs checking for `.closest('.xkit-paused-gif-container')`), ~~clean function (`wrapper.replaceWith(...wrapper.children)`)~~
Edit: That I can think of, it's somewhat convoluted to only do this on photosets …

AccessKit: Unpause all gifs on imageblock hover

---

src/scripts/tweaks.json
src/scripts/tweaks/hide_activity_notification_badge.js

'Hide activity notification badge' based on the version in Xkit 7
Option to hide the notification badge on the activity button on desktop
I got the names from the tweak in Xkit 7
no open issue, I went right to (draft) PR
I am not a "real" developer, and this is my first ever PR. Hope I did things somewhat right.

Add tweak 'Hide activity notification badge'

---

src/scripts/mass_deleter.js
src/scripts/mass_unliker.js
src/scripts/tag_replacer.js

- Tag replacer's counts will no longer be incorrect because Tumblr serves ads in the API request now (???)
- Maybe this fixes tag replacer failures (#673), but I kind of doubt it. The number always being exactly five seems too specific. (I did not observe that problem in my brief test, so I naturally didn't observe this change fixing it, either.)
My ads had `"objectType": "client_side_ad_waterfall",` and my posts had `"objectType": "post",`.
There are a whole bunch of other API calls in the codebase to check for ads and filter, I guess.
n/a

Tag Replacer/Mass Unliker/Mass Deleter: Remove ads from api response

---

src/scripts/tweaks.json
src/scripts/tweaks/show_full_note_count.js

- Adds a tweak to display full note counts (1,234) instead of compact note counts (1.2k)
Very similar to timeformat.
Using a pseudo element makes the note count non-selectable, which I personally find sort of annoying, but it looks like the note count isn't currently selectable anyway. Opinions on changing this?
resolves #576

Tweaks: Add full note count tweak

---

src/scripts/notificationblock.js

- NotificationBlock works.
The `:is()` selector used to hide notifications has less specificity than the simple class selector that Tumblr uses to set `display: flex`.
None; I need to write a PSA to people about actually submitting issues instead of just complaining in the tags.

NotificationBlock: Fix notifications not being hidden

---

src/scripts/mass_deleter.js

- Mass Deleter works in Chrome/Edge/Opera/Brave/whatever.
- Mass Deleter's date input respects time zones.
`<input type="datetime-local">`elements do not have a `valueAsDate` property in Chromium and do not respect time zones in either Chromium or Firefox. Fixed using the suggestions in the linked issues.
resolves #534, resolves #640

Mass Deleter: Fix datetime input inconsistencies; chromium crash

---

src/scripts/trim_reblogs.js

I feel like our understanding of when trim reblogs does and doesn't work must be incomplete. Nevertheless, this seems like an improvement.
- Trim Reblogs will warn the user but allow them to continue instead of silently failing if the root post cannot be retrieved to determine if the thread in question is legacy.
Maybe `.catch(() => ({ response: {} }))` is more elegant? I find it a bit hard to proofread.
resolves #563

Trim Reblogs: Fix silent failure if original root post is deleted

---

src/scripts/accesskit.json
src/scripts/tweaks.json

I don't know. I hate this. Can we put a picture of the element in question inline in the settings panel?
resolves #643

Rename "you're caught up" carousel references

---

src/scripts/accesskit/boring_tag_chiclets.js
src/scripts/vanilla_video.js

"Chiclet" doesn't look like a word anymore.
Two fixes to the handling of the animated "chiclet" elements in the dashboard (ex-"you're caught up!") carousel and https://www.tumblr.com/timeline/trending:
- Prevents Vanilla Videos from messing with chiclet appearance
- Fixes AccessKit's de-animation function
Vanilla Video: I don't know if there are videos that should be included that do not use the `videoPlayer` class.
resolves #695 (though it mentions more work that is a good idea)
addresses the core issue in #696, but does not implement its suggestion of improved functionality (could update that issue or close it and create a new enhancement issue)

Fix animated chiclet handling

---

src/scripts/scroll_to_bottom.js

- Scroll to bottom's button correctly turns yellow when active.
- Scroll to bottom correctly stops when it gets to the "bottom" of the page.
- ~~Scroll to bottom stops if you open the blog view modal while scrolling (otherwise it would continue in the background; #488 was not implemented)~~
- Minor visual fix on non-glass /blog/view pages, which have a visible scroll to top button but no visible scroll to bottom button (as per reasoning in #488)
Note: the script does not work on https://www.tumblr.com/following before or after this PR due to Tumblr quirks (there isn't a persistent loading indicator on the page and it looks to me like the site doesn't change behavior when you get to the end of the list)
n/a
resolves #712
addresses only the comment in #619 ("scrolling doesn't stop when …

Scroll to Bottom: Stop at bottom + Fix button color

---

src/scripts/accesskit/boring_tag_chiclets.js

...Surely it's not this easy?
- Pauses the animated chiclets in the unnamed-carousel-formerly-known-as-"you're-caught-up!" to de-animate them.
resolves #729

AccessKit de-animated carousel: Pause background instead of removing

---

src/scripts/accesskit.css

- Newlines in image alt text are displayed in AccessKit's visible alt text display instead of ignored. This matches Tumblr's alt text display.
Pretty sure this doesn't mess with any of our other fixes probably maybe.
n/a

AccessKit Visible Alt Text: Keep newlines

---

src/scripts/tweaks/unsticky_tab_bar.js

- The unsticky tab bar tweak should not sometimes fail.
I don't actually know how to test this, as usually it works fine as is, and I don't know how to get the XKit Rewritten rule applied before the Redpop one or how that could possibly happen.
resolves #759

Tweaks: Increase unsticky tab bar tweak consistency

---

src/util/sidebar.js

- Sidebar items are not inserted inconsistently into the blog view container.
This used to be inconsistent (the standalone blog view would have sidebar items sometimes, depending on which sidebar items Tumblr inserted and which DOM structure they used; the modal blog view would never have them).
resolves #720

Sidebar utility: Don't insert items in /blog/view

---

src/scripts/scroll_to_bottom.js

Realistically, don't worry about it. A slow selector rule is just an API request throttle in disguise anyway (as if we _did_ want to throttle scroll to bottom on purpose to make it close to holding pagedown, the delay should ideally be synchronous CPU load so there's no flickering effect.)
- Scroll to Bottom is slightly faster.
The last selector in a single querySelector rule is evaluated on every DOM element and will short circuit when it fails to match around 99.995% of the time, making the descendent selectors irrelevant. `loader` has, at the time of writing, 33 entries in the css map, while `knightRiderLoader` has one, so this is a ~33x speedup of the selector even though it's a longer string.
Mostly just thought that was cool to note.
n/a

Scroll to Bottom: minor performance improvement

---

src/scripts/quick_reblog.css
src/scripts/quick_reblog.js
src/scripts/quick_reblog.json

- Adds an option to display avatars beside the Quick Reblog blog selector.
I threw CSS at the wall until the select element correctly resized. Can you do this without `display: flex` and `flex: none` (and a bunch of manual padding)? Probably, but apparently I can't figure out how to.
Quick Reblog could use a bit of a rewrite to use `dom()`.
resolves #716

Quick Reblog: Display blog avatars in blog selector

---

src/browser_action/render_scripts.js

> Feels very natural, I like it. A nice point for iteration would be to exclude scripts with no preferences from this behaviour.
_Originally posted by @AprilSylph in https://github.com/AprilSylph/XKit-Rewritten/pull/817#pullrequestreview-1180588835_
This excludes scripts with no preferences from the linked behavior.
(Arguably slightly more consistent to close open preferences when toggling a script off even if the script in question has no preferences, but also arguably not, and does it matter?
- Toggle a script with preferences on/off. The visibility of its preferences dropdown should change.
- Toggle a script with no preferences on/off. The visibility of its preferences dropdown should not change.
- Open a script's preference pane, then toggle it off. This one is now inconsistent, but I …

Popup: Don't toggle script preference if empty

---

src/scripts/mass_deleter.js

Improves the visual presentation of the date in the Mass Deleter confirmation dialogue, removing d/m/y vs m/d/y ambiguity and the unnecessary seconds display and including the timezone.
| before | after |
| - | - |
|<img src="https://user-images.githubusercontent.com/8336245/187145176-7b55c49b-8f73-4bc4-b036-0641765392a0.png"> | <img src="https://user-images.githubusercontent.com/8336245/187145180-e8503f61-aaea-41d3-b0fe-d0b93510052f.png"> |
Feeds the configured page locale to Intl.DateTimeFormat even though the UI text is of course English. I think this probably makes sense...?
n/a

Mass Deleter: Improve date formatting

---

src/scripts/trim_reblogs.js

- Trim Reblogs puts up an informational message but lets you continue if you try to trim a legacy post.
I just did four legacy post trim tests and all of them worked fine the first time, so it seems silly to totally lock this out.
Honestly, if this works well enough, maybe it doesn't need a second modal and it can just be added to the confirmation modal?
`await new Promise` can serve as a cutesy way to stop a logic flow while enabling a resume button, but there are certainly more normal ways.
n/a

Trim Reblogs: allow legacy trimming with warning

---

src/scripts/quick_tags.js

Implements the same fix in Quick Tags as made to Trim Reblogs and the Quick Flags PR.

Quick Tags: fix default content field

---

docs/Chapter 2 - Getting started.md

The link to how to a temporary extension was broken due to Mozilla changing how colons in URLs are interpreted, in addition to changing the subdomain from `developer` to `firefox-source-docs`. 
This small PR fixes this behavior.
Just click on the link!

Fix link to Firefox extension documentation.

---

src/scripts/mutual_checker.js

This fixes mutual checker icons looking weird in the mobile/tablet view by simply reverting the previous fix, which no longer appears necessary.
Resolves #919
Load posts by a mutual with a narrow viewport. Mutual icons should not appear as they do in the screenshot in the linked issue.
Repeat when loading posts with infinite scrolling, when loading the page with a wide viewport and resizing to narrow, in the blog view modal, in the blog view non-modal, etc.

Mutual Checker: Fix misaligned reblog icons in mobile view

---

src/scripts/quick_tags.js
src/scripts/trim_reblogs.js
src/util/tumblr_helpers.js

This primarily serves to ensure that Quick Tags has no side effects. Makes sense to do anyway, though, I think.
Does this need default values to handle missing data?
As proposed in #838, this creates a utility function that encapsulates the logic for, "I want to edit a post using the NPF API endpoints; what do I start with so that I don't change anything besides what I want to change?" It takes the JSON response from the `/posts/{post-id}` GET request, removes irrelevant fields, and applies a few transformations, which Quick Tags and Trim Reblogs both had implemented separately.
It ensures that there is one place to add future properties that should be passed through or future transformations that should be added.
The functional change here is passing through `can_be_tipped` (which is …

Create NPF edit parameter utility

---

src/scripts/quick_reblog.json

> the 100 default is probably just for the sake of browser.storage.sync, which we do not use anymore, so yes please set it higher

Quick Reblog: Increase default remembered post storage

---

src/scripts/tweaks.json
src/scripts/tweaks/no_live.js

Yeah, alright.
Adds a tweak that hides the Tumblr Live carousel at the top of the dashboard.
(No, we will not hide the Tumblr Live button and make the feature entirely inaccessible.)
~~n/a; no maintainer has this element right now~~ decide where in the tweaks list this goes

New tweak: Hide Tumblr Live carousel

---

src/scripts/tweaks/no_live.js

And this is why we don't just paste the first draft code and PR it. I have brought shame upon my household.
This fixes a crash when one hard-loads tumblr.com/live that occurs since I didn't exclude other Live iframes from processing or handle their existence in the processing code.
n/a, I am _very_ trustworthy this time

Tweaks: Fix live carousel tweak

---

src/scripts/trim_reblogs.js

This mentions an edit with the _legacy post editor or the_ previous XKit version as a blanket possible reason for a post appearing as legacy in the Trim Reblogs warning popup.
Resolves #957.
Draft a reblog of  https://www.tumblr.com/transienttest/708567905092157440/beta-reblog-2. Try trimming it. Verify that the UI copy makes sense and looks good.

Trim Reblogs: Mention legacy edits + legacy XKit in legacy post warning

---

src/content_scripts/sidebar.css
src/scripts/tag_tracking_plus.js
src/util/sidebar.js

Exactly as described in the linked issue, this changes the DOM element used for clickable sidebar buttons to `<a role="button">`, allowing users to right-click or control-click them to open the ones created by Tag Tracking+ in new tabs. It implements the soft navigation helper we previously created to make regular clicks on these buttons much faster.
Resolves #854, #933

Tag Tracking+: Support control-click + right-click + use soft nav

---

src/scripts/scroll_to_bottom.js

As discussed in #975, this allows Scroll to Bottom to function on the non-modal form of the blog view that can be opened by directly navigating to e.g. https://www.tumblr.com/april. (It already did besides that we locked it out for consistency and out of a concern for being rate limited when doing so; this just removes the lockout.)
It doesn't add functionality to work in the modal blog view; that's more complicated.
Resolves #975, since the lockout can't malfunction if it's gone... except that now the reverse actually happens: the scroll to top and scroll to bottom buttons appear erroneously in the modal form of the blog view and will action on the background page. This is, of course, still a redpop bug.
Resolves #731.
Navigate to https://www.tumblr.com/april. Ensure scroll to bottom …

Scroll to bottom: Don't deactivate on "embedded blog view"

---

src/scripts/mass_unliker.js

This only shows the Mass Unliker sidebar button on the likes page. It's the kind of thing you use extremely infrequently, and I think it would make sense for a user to look for it here.
- Navigate to https://www.tumblr.com/likes. Confirm that Mass Unliker appears.
- Navigate to https://www.tumblr.com/likes/. Confirm that Mass Unliker appears.
- Navigate elsewhere. Mass Unliker should not appear in the sidebar.

Mass Unliker: Only show sidebar button on likes page

---

src/util/sidebar.js

This prevents sidebar items from being added to the settings page.
There is nothing fundamentally wrong with the idea of XKit adding stuff to settings, I guess, but it's a) seemingly not intended for any script so far, b) kind of weird, and c) at the very least, in the wrong place, taking up space above the blogs selector.
Enable Tag Tracking+/Tag Replacer. Navigate to the settings page and confirm that neither appears. Navigate elsewhere and confirm that they do.

Exclude settings page from sidebar insertion

---

src/content_scripts/main.js

This prevents XKit from silently failing to load some scripts on slow computers in certain scenarios in Chromium-based browsers or Safari; see the linked issue, https://github.com/AprilSylph/XKit-Rewritten/pull/945#issuecomment-1439428253, and https://github.com/sveltejs/kit/issues/7805#issuecomment-1330078207 for background.
The bug appears to be that it is possible for dynamic imports to fail when multiple dynamic imports attempt to load the same module file simultaneously during the import waterfall when that module is waiting on a top level await statement.
Ensuring that the modules in question have resolved already appears to be the minimum change necessary to fix this.
We have discussed other solutions (completely removing top level await from imported utils, #1017) and improvements …

Fix Chromium/Safari script loading inconsistency

---

src/util/notifications.js

Minor refactor we forgot to do once keyToCss was synchronous: this removes some unused `await`s in notifications.js.
Confirm that notifications still work, e.g. by drafting a reblog with quick reblog.

remove unused awaits from notification util

---

src/scripts/seen_posts.css
src/scripts/seen_posts.js
src/scripts/seen_posts.json

I'm stealing this branch (#870) from @char-lock to add a `lengthenTimelines` function!
(This includes a rebase off of master to take advantage of #891, allowing the `timeline` variable to be a string.)
As per the linked issue, adds a preference to the Seen Posts script to allow users to hide seen posts on the dashboard using a CSS style.
Resolves #869.
User should be able to browse as usual, but when their dashboard updates with new posts, any posts they have viewed will be hidden, leaving only new posts and old ones that have not been viewed.

Seen Posts: Hide seen posts completely

---

src/content_scripts/control_buttons.css
src/scripts/quick_tags.js
src/scripts/trim_reblogs.js
src/util/control_buttons.js

Seeing a lot of user reports that Trim Reblogs is broken and I would really like to know if it's a button add failure or a misunderstanding about which posts should be trimmable. Hence:
As described in the linked issue, this disables the trim button on editable but untrimmable posts, rather than not adding it at all.
This uses the native dom `disabled` attribute on the button element and moves the event handlers on control buttons to the button element itself.
Resolves #958.
- Confirm that e.g. Quick Tags works as expected.
- Try to press the Trim Reblogs button on an original post, a reblog with no added content and only one trail item, and a post with enough content to trim.

Trim Reblogs: always show trim button

---

src/scripts/no_recommended/hide_recommended_posts.js

This turns No Recommended's hide recommended posts tweak off once more than (an arbitrary) 10 posts in a row are recommendations.
This prevents the endless-scrolling-enabled dashboard from continually loading new content if part of one's dash is entirely recommended posts, which appears to be happening on my account if I scroll back enough (and might be true on a new user's dash as well). This saves server load and memory, of course.
~~I think this is fine to do without any UI copy updates. A fancier version could apply a CSS style to the element with `precedingHiddenPosts(postElement) === 10` that gives it a `before` with a message about too many recommended posts to hide.~~ actually you know what here
If your dash does the same thing as mine: scroll far enough down your dashboard that …

No Recommended: Stop hiding when all posts are recommended

---

src/scripts/open_in_tabs.js

This fixes #1019 by applying pageModifications targeting `a[role="link"][target="_blank"]` and attaching click event listener. 
- While Open in Tabs is enabled, access the modals as shown the in the images below. 
- Click on the any of the links (e.g. blog name)
- On-dashboard blog view won't show but instead it will open a new tab as intended.

Open in Tabs: Fix in blog card modals/blog view modals

---

src/scripts/tweaks/unsticky_tab_bar.js

Goal is to provide a fix in #968 by changing `position: static !important;` to `position: relative !important; top: 0 !important;`. 
- Change `position: static !important;` to `position: relative !important; top: 0 !important;`.  https://github.com/AprilSylph/XKit-Rewritten/blob/c4a0a29d3aad83ab4dd49279fd0a9672f12907c2/src/scripts/tweaks/unsticky_tab_bar.js#L5
- Enable Unsticky Tab Bar tweak
- Go to your dashboard > your tags
- Click "filter by tags"
Confirm the fix works if it shows:

Tweaks: Fix "your tags" dropdown visual issue of Unsticky Tab Bar

---

src/scripts/seen_posts.css

This fixes #986 by adding a media rule with the max-width of 990px, and applying `opacity: 1;` to the other images besides the first image (avatar). 
- Turn on Seen Posts > Dim avatars
- View a post with checkmarks 
- Refresh and locate the same post
- Change the window size to 990px or lower for the mobile view 
Before:
After:

Seen Posts: Fix faded checkmarks in mobile view

---

src/util/mega_editor.js

I don't think I'm doing this right.
This ensures that a non-201 response to the mega editor endpoint actually triggers catch handlers in scripts with some useful information. Without this change, `inject()` serializes the non-201 `Response` object to `{}` and resolves, so scripts think their edits succeeded when they actually did not.
I'm not at all familiar with how the inject error code works or how javascript errors work in general. But the inject code clearly expects a rejected promise containing an error, which `fetch` doesn't natively create, so, this is a manual way to do that? Is there a better way?
The other thing I considered was, can you coerce a `Response` to be serializable (e.g. via `Object.fromEntries(Object.entries(response))` and then always resolve through the inject …

Mega-Editor Utility: Pass errors correctly

---

src/scripts/tweaks/no_live.js

This updates the CSS selector used to hide the Tumblr live carousel. I don't actually think the iframe selector is necessary, but I didn't save the HTML of the old element, so better safe than sorry.
Resolves #1047.
Enable Tweaks and the tweak to hide the Live carousel on an account with the new, iframe-less carousel. Confirm that it works.

update live carousel selector

---

src/scripts/quote_replies.css
src/scripts/quote_replies.js

Adds Quote Replies buttons to the activity dropdown.
idk man. css or whatever. there's not a lot of space in there
Resolves #862.
Use Quote Replies on the activity page. Confirm that it still works as expected.
Use Quote Replies from the notification dropdown. Confirm that it works as expected.
Comment the `@media (hover: hover)` CSS rule section or use a touchscreen and confirm that nothing explodes and the Quote Replies buttons are still visible.

Quote Replies: Activate in notification dropdown

---

src/scripts/tweaks.json
src/scripts/tweaks/hide_blaze_tip_labels.js

Booting up the ol' "xkit rewritten" time tracker entry. 
This adds a tweak that hides the text labels on the blaze and tip buttons in the post footer. Once you've seen them a couple hundred times, you know what they are, I figure.
Resolves #1055.
Enable the new tweak. Confirm that blaze and tip icons on original posts no longer have text labels, but that they still appear as expected.

New Tweak: Hide the labels on the Blaze and Tip buttons

---

src/scripts/cleanfeed.js
src/scripts/cleanfeed.json

This includes mature-labeled posts along with posts by "flagged" blogs in CleanFeed. It doesn't add any additional options or process nudity/violence/alcohol flags separately, opting for the simplest solution.
Resolves #947.

CleanFeed: Always process mature-labeled posts

---

src/scripts/tweaks.json
src/scripts/tweaks/restore_attribution_links.js

Tumblr recently removed the links to the actual post (and the reblogged post, if any) from the header, and [apparently intends](https://www.tumblr.com/changes/718768407758225408/tuesday-may-30th-2023) to keep this change.
However, the links are helpful for many people, so now there is a tweak which restores them.
Fixes #1077.
(Note: the tweak does not attempt to remove the helpful links when disabled. Of course, they will be "removed" on next page reload.)
1. Enable "Restore links to individual posts in the post header" in the Tweaks module.
2. Examine the links on the blog names in the post attribution header.
I wasn't entirely sure which arguments to use with `filterPostElements`, so I used "Hide Liked Posts" as a model. Feel free to suggest a better way.

New Tweak: Restore post links in attribution header

---

src/util/sidebar.js

Speedrun, let's go.
Updates the sidebar utility for the upcoming vertical nav layout and the current updated mobile navigation drawer.
~~The significant code change here is that because we need to prioritize the sidebar over the navigation section when both exist on the page (in the wrong DOM order), I re-query the candidate elements in the pageModifications callback in priority order instead of using the element list given by pageModifications itself.~~ never mind. I can read.
Question: Were XKit's sidebar items supposed to be at the top or the bottom of the mobile navigation drawer? I actually don't remember.
Load XKit Rewritten on an account with the new vertical nav layout and an account without it. Enable limit checker and confirm that the sidebar item appears at the bottom of the …

Vertical nav layout: Update sidebar utility

---

src/scripts/tweaks/unsticky_tab_bar.js

Updates the unsticky tab bar tweak for the upcoming vertical nav layout.
Presumably the `newDesktopLayout` CSS class will eventually go away, at which point this will break again?

Vertical nav layout: Update unsticky tab bar tweak

---

src/scripts/quote_replies.js

For the record, my preference for not hiding the quote replies button on non-hovered activity items was partially so that this kind of thing would have been more obvious and would have been fixed weeks/months ago :D
This fixes Quote Replies having been completely broken by small changes in the latest update to the activity items. (That I can tell, the extra div element in the dropdown serves no purpose and might have been a "mistake," but whatever :D)
This was not reported by anyone, but was just mentioned in the tags of a few posts! I had not noticed it. Please, anyone who is reading this: if you find that XKit Rewritten is broken by an update, **tell us about it**!
**edit:** resolves #1126
Confirm that Quote Replies buttons appear next to mentions in the activity dropdown menu and on …

Quote Replies: Fix script not functioning

---

src/scripts/accesskit/disable_animations.js

Prevents the "disable animations" feature from breaking photoset creation in the new post editor in Chromium-based browsers (see linked issue for repro details).
Resolves #1100.
In Chromium:
Enable AccessKit and the disable animations function. Insert two separate images into the new (gutenblr) post editor. Try to drag one beside the other with the four-squares (dragHandle) button in the top left and ensure the drag animation works normally and the photoset is successfully created.

AccessKit: Exclude post editor contents from "disable animations"

---

src/scripts/collapsed_queue.js

This ensures that Collapsed Queue only runs in the desired locations, even when no locations are selected.
I couldn't think of a way to do this using regular expressions besides adding an obviously-invalid string to the array of alternate matches, which would have been less clear in meaning than this.
Resolves #1174.
Confirm that all four combinations of selected options (none, drafts, queue, both) correctly do or do not cause the script to be active on the queue and drafts page.

Collapsed Queue: Prevent running with no options selected

---

src/scripts/tweaks/no_live.js

On accounts created after May 8th, 2023, the default tab is "for you" and thus the Live carousel appears on the "for you" tab. I was previously overly cautious (e.g. in case Staff added some sort of Live-specific tab where this carousel was important; there is precedent for this with e.g. the blog subs tab and its blog carousel) and only made the Live tweak active on the following tab, which caused it to be inactive on these accounts.
This removes the timeline check, ensuring that the carousel is hidden on any tab. This seems prudent if the default tab may become customizable.
Resolves #1180.
- Log into an account with the "for you" tab as the default.
- Confirm that the "hide the Live carousel" tweak works on https://www.tumblr.com/ and https://www.tumblr.com/dashboard/stuff_for_you.
- …

Tweaks: Fix Live carousel tweak on "for you" default accounts

---

docs/Chapter 4.1 - Feature manifests.md
src/browser_action/configuration.css
src/browser_action/render_scripts.js
src/scripts/timestamps.json

resolves #1058
As per the linked issue and the discussion in its comments, this adds a "deprecated" property to script manifests that will hide them unless they're enabled at the time of deprecation (still ironing out details as I write this), and deprecates Timestamps.
- Load a branch without this PR.
- Optionally, enable and then disable and/or play with the settings of Timestamps.
- Switch to a branch with this PR.
- Confirm that Timestamps disappears from XKit's preferences.
Restart with clean storage. (I ctrl-c'd `npm start`; importing `{}` into the backup interface doesn't currently wipe your storage.)
- Load a branch without this PR.
- Enable Timestamps.
- Switch to a branch with this PR.
- Confirm that Timestamps still appears in XKit's preferences.
- Disable Timestamps.
- Confirm …

Implement feature deprecation

---

src/scripts/show_originals.css
src/scripts/show_originals.js

This moves Show Originals' control element out of (above) the timeline element to avoid issues with the "virtual scroller" Tumblr feature.
This is a UI change on pages like https://www.tumblr.com/timeline/blog_subscriptions, but I don't think it's a big deal.
Not completely addressed: #1196. There is still a bunch of scrollbar thrashing that I'll have to investigate. This makes the feature work, though.

Show Originals: Fix basic functionality with "virtual scroller" experiment

---

src/scripts/tweaks/hide_blaze_tip_labels.js

This excludes the label following an ~~active~~ pending blaze button from the "Hide the 'blaze' and 'tip' button labels" tweak.
You know what, I don't actually know how one would easily test this. But, hypothetically: enable the relevant tweak, blaze a post, and check that the label indicating that it is pending is visible while other labels continue to be hidden.

Tweaks: Prevent hiding pending blaze status label

---

src/scripts/anti_capitalism.js
src/scripts/mutual_checker.css
src/scripts/mutual_checker.js
src/scripts/no_recommended/hide_blog_carousels.js
src/scripts/no_recommended/hide_radar.js
src/scripts/no_recommended/hide_recommended_blogs.js
src/scripts/no_recommended/hide_recommended_posts.js
src/scripts/no_recommended/hide_tag_carousels.js
src/scripts/postblock.css
src/scripts/postblock.js
src/scripts/show_originals.css
src/scripts/show_originals.js
src/scripts/tweaks/caught_up_line.js
src/scripts/tweaks/hide_filtered_posts.js
src/scripts/tweaks/hide_liked_posts.js
src/scripts/tweaks/hide_my_posts.js
src/scripts/tweaks/no_live.js
src/util/interface.js

As per discussion #1207, this fixes and improves content hiding on accounts with the "virtual scroller" experiment. This experiment wraps timeline items in `cell` wrappers and unmounts the wrapper contents when they are far off the screen.
This PR:
- Implements a helper function (`closestTimelineItem`—open to better names) which finds either the `cell` or `listTimelineObject` containing an element, unifying logic between accounts with and without the experiment.
- Places the content-hiding class on the `cell` when it exists, ensuring that content is still hidden when it is re-mounted on scroll, preventing scrollbar jumps.
- Changes from class names to data attributes for all content hiding, preventing a changed classname from the React code overwriting the hidden property on a cell
Seen …

Fix/improve content hiding with "virtual scroller" experiment

---

src/util/mutations.js

You know I had to do it to em
(actually, I don't know what that meme means or where it comes from. hopefully it's not, like, racist. anyway.)
This improves the behavior discussed in https://github.com/AprilSylph/XKit-Rewritten/discussions/1207#discussioncomment-6747508 somewhat by running `pageModifications` instantly instead of in a `requestAnimationFrame` callback if and only if the modification in question is the mount of a post (or whatever) into a virtual scroll experiment `cell` element. These mounts are currently (often?) run using `requestAnimationFrame`, which means that our trick of delaying `pageModifications` processing only within the current frame doesn't work and causes a render without our modifications for one frame.
It leaves the `requestAnimationFrame` trick (debounce, …

Prevent visible UI flicker when processing new posts

---

src/scripts/show_originals.css
src/scripts/show_originals.js

This moves the DOM position of the Show Originals controls element (again) to be inside the timeline element, but outside the scroll container, ensuring that it doesn't move around.
Using `controls ~ div > post` as a selector is perhaps a little fragile (if there are two nested container divs in some future timeline DOM change, it'll break), but considering that I had to make a change at all, apparently anything can be a little fragile. I would have guessed that the "above the first post" location would be the most resilient, but in this case it wasn't, so ¯\\_(ツ)\_/¯
Resolves #1219.
With the virtual scroll experiment both on and off, I tested that the Show Originals controls functioned on the dashboard, in the blog view modal, and in the blog view modal on a specific post.

Show Originals: Fix controls element moving on resize

---

src/scripts/seen_posts.css
src/scripts/seen_posts.js

This applies the same modifications for post hiding (moving the class to the `cell` if present; using a data attribute) that fixed other scripts with the virtual scroller in #1213.
It also moves Seen Posts' `excludeClass` functionality to this method as well. This is important because double processing of posts has an unintended functional side effect with Seen Posts
Resolves #1211.
I typically:
- unrevert the test code
- enable Show Originals on the original posts view (to test interoperability)
- enable Seen Posts and scroll a bit down my dash, confirming that posts I see are marked red by the test code but not dimmed
- soft navigate somewhere else (e.g. explore)
- soft navigate back and confirm that the posts I saw and marked are dimmed
- toggle Show Originals to the all posts view
- …

Seen Posts: Fix functionality with "virtual scroller" experiment

---

src/util/preferences.js

Makes getPreferences asynchronously wait once instead of [number of preferences] times.
Part of a little project attempting to make the last tweak you enable not take like 7 seconds to actually go into effect.
This makes very little difference (couple hundred milliseconds).

Preferences util: Remove local storage loop delay

---

src/scripts/seen_posts.js

As per [my](https://github.com/AprilSylph/XKit-Rewritten/issues/1211#issuecomment-1684491464) [comments](https://github.com/AprilSylph/XKit-Rewritten/issues/1211#issuecomment-1684504017), this fixes an issue with my [previous PR](https://github.com/AprilSylph/XKit-Rewritten/pull/1221) in which unseen posts might never be marked as seen if they lose their IntersectionObserver handlers by getting unmounted.
Resolves #1211. For real this time.
With the virtual scroller enabled, I:
- put the test code in
- tried REALLY HARD to scroll aggressively and trigger the scenario where a post loses its handler and does not become marked red when seen
- didn't observe that
- also did the tests specified in #1221

Seen Posts: Fix functionality with "virtual scroller" experiment (better)

---

src/scripts/cleanfeed.js
src/scripts/cleanfeed.json

Resolves [#1178](https://github.com/AprilSylph/XKit-Rewritten/issues/1178)
Adds an option to treat specified tags as mature in the same way specified blogs can be treated as mature
Add a tag to the text field in the CleanFeed options and view a post with said tag

CleanFeed: Add option to treat specified tags as mature

---

src/manifest.json
src/scripts/mutual_checker.js
src/scripts/tweaks/restore_attribution_links.js
src/util/interface.js

Updates our selectors for post author attribution, which we have to be careful does not include reblog parent attribution. This fixes Mutual Checker and the post author part of the "Restore links to individual posts in the post header" tweak.
For Mutual Checker, because of how popover wrappers work, we need to insert the mutual icon _before_ the wrapper and not _inside_ it - otherwise, on click, the DOM modification (the icon) will be cleared. This necessitated a new method for walking up the DOM tree to find the outermost popover wrapper - there is always one nested inside another, for some reason.
Fixes #1237
Fixes #1238
1. Load the modified addon in your browser of choice
2. Enable Mutual Checker
3. Enable Tweaks
4. Enable Tweaks &rarr; "Restore links to individual posts in the post …

update post author attribution targeting

---

src/scripts/tweaks.json
src/scripts/tweaks/hide_following_notification_badge.js

Similar to the the tweak that hides the notification badge for activity, this adds one that hides the notification badge for new posts on your chronological dashboard (following feed/home button). I've wanted this for years, people assume the activity one does this already, and it's particularly relevant as people are using it as a specific criticism of the vertical nav layout.
I am actually... confused? because I currently only see the badge in question appearing in the vertical nav layout? But a) I remember wanting this for ages so it must have been a thing, and b) the linked discussion definitely implies that it was a thing very recently?
Resolves #1132.
- Confirm that the badges in both the vertical nav layout's "home" nav item and "following" dashboard tab bar tab are hidden by this …

New Tweak: Hide the home/following notification badge

---

src/scripts/tag_tracking_plus.css
src/scripts/tag_tracking_plus.js
src/util/sidebar.js

This fixes the race condition causing Tag Tracking+ to only mark one post at a time as seen using NotificationBlock's storage architecture (keep a local copy of the storage in memory and don't rely on setting/getting local storage; using an `onStorageChanged` callback to grab any changes made by another instance of the extension).
Note: for all I know it's possible to get erroneous behavior with this method, too, albeit quite difficult in practice. In theory, if one did two back-to-back storage edits, which both asynchronously called `browser.storage.local.set`, this could maybe trigger `onStorageChanged` asynchronously twice, and if any code ran in between those two it would get the wrong data. I haven't seen `onStorageChanged` trigger twice though, so, eh. Anyway.
> This also—and I will …

Tag Tracking+: Fix race condition and improve preference change behavior with `onStorageChanged`

---

src/scripts/tweaks.json
src/scripts/tweaks/following_tab.js

Is Staff planning to add a feature that makes your first dashboard tab customizable **and the default** (or that remembers your last-selected dashboard tab or something) any time soon? If yes, this is obviously pointless. I, however, was not sure if that was the implication of
> We are also working on making dashboard tabs even more customizable, including adding the ability to choose which tab appears first.
Adds a tweak that forces navigation to tumblr.com and tumblr.com/dashboard to actually point to the "Following" dashboard tab instead of the "For You" dashboard tab, as it does for accounts created after May 8th, 2023.
I will probably publish an equivalent to this as a userscript (already written) and then no-op it when it is no longer needed if we don't want to add it to XKit and …

New Tweak: Force the default dashboard tab to "Following"

---

src/manifest.json

As per the linked issue, this makes the tooltip that appears when you mouse over the extension's control icon the name of the extension, to be consistent with other extensions (and as I think makes the most sense).
Currently, this does not change the actual title attribute of the preference window, i.e. if you open it standalone (I hadn't realized this was separate from the button tooltip). I have no particular opinion if it should be "XKit Control Panel," "XKit Rewritten Control Panel," "XKit Rewritten," whatever.
Resolves #988.
Ensure that the tooltip changes as desired in both Firefox and Chromium.

Set browser action tooltip to "XKit Rewritten"

---

src/scripts/trim_reblogs.js

This adds a warning message when one uses Trim Reblogs on an ask post, noting that it causes post corruption on blog themes.
Copy improvement suggestions are welcome.
Resolves #1089.
- Use Trim Reblogs on an ask.
- Use Trim Reblogs on a legacy post (I get them from https://www.tumblr.com/best-of-reblogs).

Trim Reblogs: Add warning about trimming asks

---

src/scripts/cleanfeed.css

Fixes Cleanfeed not filtering certain "unstretched" media by changing the selector that targets media.
Find or make a post that is filtered by your Cleanfeed preferences, add inline styling to the media `<figure>` element. The element should still be hidden as normal. The filter should also still ignore anon avatars in asks.
Resolves #1277

CleanFeed: process unstretched media

---

src/scripts/notificationblock.js
src/scripts/notificationblock.json

This adds a note to the NotificationBlock interface about the new "Mute Notifications" native feature.
It also—and I'm fine with not doing this if it seems confusing—changes the terminology throughout the NotificationBlock UI to "hide," as the native feature is much closer to what "block" actually means than what the script does. It does not update the name of the script itself, although we could do that too (it would still start with "Notification").
Copy improvement suggestions are welcome.
Resolves #1173.
n/a

NotificationBlock: Add note about "Mute Notifications"

---

src/scripts/tag_tracking_plus.js

As per the linked issue, this catches errors thrown by the refresh function in Tag Tracking+ and displays "⚠" instead of a count if it does so.
Resolves #847.
Un-revert the reverted commit and confirm that the script continues to update the non-errored tags.

Tag Tracking+: add error handling to `refreshCount`

---

src/scripts/accesskit.css
src/scripts/accesskit/disable_gifs.js

This implements a smaller version of the disable gifs overlay label for use on small images like the previews in the blog card modal.
View paused GIFs in the explore sidebar, in a blog card modal, in the search/tagged page in masonry view, etc. Small images should have small GIF labels; hopefully this should feel natural.

AccessKit Disable Gifs: Use miniature labels on small images

---

src/scripts/scroll_to_bottom.js

This fixes Scroll to Bottom's loader selection code being out of date. The element containing the loader beneath a timeline now has CSS classes equivalent to `.container.condensed`.
Resolves #1286.
I don't love using "container" as a translated CSS class key because it has so many classnames associated with it, but oh well.
Use Scroll to Bottom on a dashboard, on a channel page, on the followers page of a blog, and the activity page. Confirm that it does not stop scrolling after the first page and does stop scrolling when it runs out of content.
(This continues to not work on the following page, as Tumblr does not show a loading element there.)

Scroll to Bottom: Fix scrolling stopping after one page

---

src/scripts/show_originals.js
src/util/on_navigation.js

This implements a wrapper around window.tumblr.on('navigation') so that XKit Rewritten can subscribe to soft navigation events.
More elegant form of #453.
Potentially useful for simplifying logic where something must happen when a navigation event removes an element from the page (as one can't detect removals with `pageModifications`), but when using both one can't be sure of the order they're fired in and thus must be careful, presumably.

Experiment: Create navigation utility

---

src/scripts/notificationblock.js
src/util/interface.js
src/util/mutations.js
src/util/react_props.js

More utils for the activity feed as suggested by #1303 and alters Notification Block to use the new utils. Facilitates future notification-based manipulation features, such as #1301.
- Open Tumblr with Notification Blocker enabled.
- Use the UI to block original posts that has notifications.
- Navigate to the activity page or trigger the popup.
- Ensure that there are no new errors in console and that no notifications for the blocked posts pop up.

Activity feed utils

---

src/scripts/tag_tracking_plus.css

Addresses #1268 using CSS.
- Open Tumblr with Tag Tracker+ enabled.
- Visually confirm that the space exists when there are no tags either unread or tracked.

Add a little space to Tag Tracker label 

---

src/scripts/tweaks.json
src/scripts/tweaks/unsticky_post_avatars.js

Fixes #1265 by removing the config in the JSON and removing the file. This doesn't address anything functional, just removes the option since the new official Tumblr layout doesn't have any sticky effect. (There's an issue to reinstate it though, #1310.)
1. Open XKit Tweaks menu.
2. Ensure that there are no errors in console and that "Remove the sticky effect from post avatars" option is not in the menu.

Remove "Remove the sticky effect from post avatars" tweak

---

src/scripts/no_recommended/hide_radar.js
src/scripts/no_recommended/hide_recommended_blogs.js

Fixes the No Recommended options to hide the recommended blogs sidebar item and the radar.
Resolves #1316.
Enable No Recommended.
- Toggle the "Hide recommended blogs in the sidebar" option and confirm that it functions correctly (including on tagged pages, the code for which was not changed).
- Toggle the "Hide the Tumblr Radar" option and confirm that it functions correctly.

No Recommended: Fix blog sidebar/radar hiding

---

src/scripts/mutual_checker.css
src/scripts/mutual_checker.js
src/scripts/mutual_checker.json

Addresses #1301 by adding a new option to only show notifications from mutuals. Added common functionality (ie: unburying notifications) to utils that may be useful to other activity page features such as Notification Block. 
- Open Tumblr with Mutual Checker and notification filter enabled.
- Navigate to the activity page or trigger the popup.
- Ensure that there are no errors in console and that only mutual notifications pop up.
I'm new to contributing to open source so any and all kind feedback is welcomed!

Mutual checker notification filter

---

src/scripts/cleanfeed.css

Prevents the "Hidden by CleanFeed" text from overlapping on certain small images, as can be seen [here](https://www.tumblr.com/meowlgbt/733113897690775552/kitty-can-be-doggy-as-a-treat).
Resolves #1324.
Enable CleanFeed, add the blog in the post above to the filter list, and view the image cover

CleanFeed: Prevent text overlapping on small images

---

src/scripts/no_recommended/hide_blog_carousels.js
src/scripts/no_recommended/hide_tag_carousels.js

Fixes #1335 by changing the blog carousel and tag card selectors to match the current element classes
```js
const blogCarouselSelector = `${listTimelineObjectSelector} ${keyToCss('blogRecommendation')}`;
```
```js
const tagCardSelector = keyToCss('tagCard');
```
- Enable the No Recommended feature and the two related preferences
- Scroll through the timeline

No Recommended: Change blog and tag carousel selectors

---

src/scripts/tweaks/caught_up_line.js

Fixes #1334 by changing the selector to match the current element classes 
```js
const tagChicletCarouselLinkSelector = `${listTimelineObjectSelector} ${keyToCss('tagChicletLink')}`;
```
- Enable the Tweaks feature and the caught up line preference
- Click the home navigation icon twice to bring the caught up line to the top of the feed

Change carousel selector for the caught up line tweak

---

src/scripts/timeformat.js

This makes Timeformat's selector more specific so that it doesn't affect `<time>` elements that it isn't supposed to.
Resolves #1289.
- Enable TimeFormat.
- Confirm that the timestamp at the top of [tumblr.com/explore/answertime](https://www.tumblr.com/explore/answertime) is not affected.
- Confirm that the timestamps of posts on the dash and the radar post are still affected.

TimeFormat: Don't format `<time>` elements outside of posts

---

src/scripts/no_recommended/hide_blog_carousels.js

Enough classname targeting.
This uses our `timelineObject` utility to read the react internal data of recommendation carousels, reliably identifying those which are blog recommendations (as opposed to tag recommendations). This is, of course, fragile to changes in the underlying API data, but it seems better than trying to target a classname, ~~since there aren't any unique "blog recommendation"y ones in this element.~~
Resolves #1346.
- Optionally unrevert the test commit for visibility
- Confirm that No Recommended's blog carousel hiding functionality works on the dashboard and on tag pages and doesn't hide tag recommendations (I did not do the latter; I can't find any)
- Confirm that No Recommended's blog carousel hiding functionality works on anywhere else blog recommendation …

No Recommended: Reliably select blog carousels via react props

---

src/scripts/tweaks/unsticky_tab_bar.js

With the removal of floating sticky avatars, our CSS rule to adjust them for the unsticky tab bar tweak isn't needed.
- confirm that the unsticky tab bar tweak still works

Tweaks: Remove unused tab bar CSS

---

src/scripts/accesskit/disable_gifs.js

A race condition can occur that causes AccessKit Disable Gifs to use miniature labels on images in a post that are the regular, full size. This happens when the post is hidden, e.g. by another XKit script, before Disable Gifs gets to process it. When the user unhides the post later (e.g. by toggling Show Originals to "all posts"), the label is visible.
This adjustment only tries to make the label miniature if `gifElement.clientWidth` exists and is nonzero. (It might be possible to trigger the wrong behavior in reverse, by loading a post with multiple gifs side by side in the masonry/grid view in a hidden state and then revealing it to now have labels that are too big, but I'm not sure we even have a script that hides posts in masonry and even if that does happen it's probably not …

AccessKit Disable Gifs: Fix unexpected mini labels (minor)

---

src/scripts/accesskit.json

[Chrome 121 supports `scrollbar-width`](https://developer.chrome.com/blog/new-in-chrome-121), so the regular-width scrollbar feature applies to it and is thus no longer Firefox-specific. This removes the mention of Firefox from its checkbox.

AccessKit: Rename regular-width scrollbars feature

---

src/scripts/timeformat.css

Resolves #1391.
- Reduce the browser viewport all the way (to the point where post bounding boxes touches the viewport edges and do not have rounded corners) or load XKit on a mobile device small enough to use this view and confirm that Timeformat works correctly on reblog trail item headers.

TimeFormat: Fix timestamps on mobile devices

---

src/scripts/quick_tags.js
src/scripts/trim_reblogs.js
src/util/control_buttons.js

Adds aria-labels and on-hover tooltips to our control buttons.
Resolves https://github.com/AprilSylph/XKit-Rewritten/issues/973.
Enable Quick Tags and/or Trim Reblogs. Mouse over the control buttons with the viewport width both greater and less than 990px and with touchscreen emulation turned on and off.

Control button util: Implement descriptive text

---

src/scripts/tweaks/hide_activity_mutuals.js

This fixes the "Hide following/mutuals indicators on notifications" tweak, which was broken by a CSS name change.
Resolves #1387.
- Confirm that "following" and "mutuals" labels are hidden in the activity popup and activity page.

Tweaks: Fix following/mutuals activity label tweak

---

src/scripts/tweaks.json
src/scripts/tweaks/hide_following_notification_badge.js
src/util/mutations.js

As discussed and prototyped in the linked issue, this is April's code that adds functionality to the `Hide the Home/Following unread badge` tweak to also hide the unread post count in the browser tab title.
Resolves #1360.

Tweaks: Remove unread post count from tab title

---

src/scripts/tweaks/hide_activity_notification_badge.js
src/scripts/tweaks/hide_following_notification_badge.js

Alternative: #1394.
This hides the mobile menu's notification badge, which is shown if you have any activity notifications and/or any new posts on your timeline, if you have the tweaks that hide either one enabled.
Given that we don't really have an easy way of only hiding it based on the state of one or the other*, I assume that this is what most people would want (?) but it's definitely not perfect.
Resolves #1256.
*maybe? it would probably involve polling react context on an interval or something?

Tweaks: Hide mobile menu badge when it's ambiguous

---

src/scripts/tweaks/caught_up_line.js

As per the linked issue, this fixes an issue where the ≤540px-width mobile layout caused the line indicator created by the `Turn the Changes/Shop/etc. links carousel into a separating line` tweak not to appear. This is due to the Tumblr frontend hiding timeline elements with less than a certain height value, and that value not changing with the reduced spacing when the layout changes.
This adds 2px of spacing above and below the line in this layout to fix this. (3px is the total required, but that wouldn't be symmetrical.)
Resolves #1398.
- Open your dash with a viewport width of <540px (zooming in makes this easier on a desktop browser).
- Confirm that the affected tweak works and the visual spacing above and below the line indicator appears symmetrical.

Tweaks: Fix "Caught-up line" not appearing on mobile devices

---

src/scripts/tweaks/caught_up_line.js

This prevents the caught up line tweak (officially `Turn the Changes/Shop/etc. links carousel into a separating line`) from affecting the carousel atop the "your tags" tab at https://www.tumblr.com/dashboard/hubs.
Specifying the dashboard in question seemed like the easiest way to do this, as there is very little that differentiates the carousel we want to hide from a followed tags carousel. They mostly seem to use the same rendering code; the API response that makes the thing we want to hide (I still call it the "you're caught up" carousel) has `objectType: "followed_tag_carousel_card"`.
Resolves #1375.
- Confirm that the tweak in question still works on https://www.tumblr.com/ / https://www.tumblr.com/dashboard / https://www.tumblr.com/dashboard/following.
- Confirm that the tweak in …

Tweaks: Fix carousel hiding affecting "your tags" tab

---

src/scripts/accesskit/visible_alt_text.js

Fun fact: At time of posting, the default alt text of an image added to the editor when the UI language is set to Spanish is lowercase. `window.tumblr.languageData` doesn't have this variation, as the same key ("Image") corresponds to both case variations ("Imagen" / "imagen") and of course a javascript key-value object can only have one of them.
This means that the "only show image descriptions" alt text mode doesn't work in Spanish (and in general that we're relying on whoever does Tumblr's translations not to put different values in any case where multiple values correspond to a single key). This PR fixes this in the case of visible alt text and specifically cases differing.
- Enable visible alt text and the `Only show image descriptions` option.
- Change the UI language to Spanish.
- …

AccessKit Visible Alt Text: Fix "imagen" appearing in Spanish

---

src/scripts/quick_tags.js

> This would be a lot of work to fix any way that I can think of and is fairly minor, so my guess is that we won't fix it
Eh, it wasn't actually _that_ many lines of code.
This:
- Uses Trim Reblogs' button-adding code in Quick Tags
- Extracts the "add fake tags" code into a function and re-applies it to posts when an edited post is added back to the page by the "virtual scroller" code.
Resolves #1380.
- Add tags to a post with Quick Tags
- Scroll away until the post disappears, then scroll back
- Confirm that the post still appears to have the added tags
- Edit the post with the normal Tumblr editor, changing its tags again
- Scroll away until the post disappears, then scroll back
- Confirm that no erroneous changes persist on the post

Quick Tags: Preserve tags when scrolling

---

src/scripts/show_originals.js
src/scripts/show_originals.json

As per the linked issue, this adds an option to Show Originals that shows reblogs if you don't follow the account that's being reblogged. This makes it into a "my friends all reblog each other and I don't really need to see the same content a bunch of times" filter.
Tried it out myself and I can definitely see the appeal, though my dash is mostly people who don't know each other and so most of the content is new to me.
Resolves #1386.
If desired, unrevert the test commit, enable Show Originals and both "always show reblogs" options, go to the "all posts" tab, and observe that reblogs that you wouldn't expect to see on your dash twice are highlighted green, while self reblogs and reblogs of other users you follow are highlighted red.

Show Originals: Add option to hide only reblogs you follow

---

src/scripts/quick_tags.js

Refactors a few bits of code in Quick Tags that I found confusing on first read. They might originate from before `dom()`; I don't recall. Should result in no functional changes.
- Confirm that the quick tags post popup appears correctly and works correctly, including fake tag generation.
- Confirm that the quick tags editor popup appears correctly and works correctly.

Quick Tags: Minor refactors

---

.github/workflows/release-notes.yml

Re: #1454
Adds an optional input to the release notes action allowing the user to specify the version to begin notes from.
Tested with a manual argument on the source fork: https://github.com/marcustyphoon/XKit-Rewritten/actions/runs/9070322977
Tested without a manual argument, very sloppily, on a branch of the source fork: https://github.com/marcustyphoon/XKit-Rewritten/actions/runs/9070372444

Actions: Allow release note generation for old versions

---

.github/workflows/release-notes.yml

- Removes the previous artifact-based creation steps
- Wraps the output in a code block (with Markdown syntax formatting!)
Much more convenient. Allows release notes to be copied with a single click, without needing to download anything, and without even needing to scroll past anything.
Successful run: https://github.com/AprilSylph/XKit-Rewritten/actions/runs/9087088473
It seems that escaping the backticks is necessary. The [initial run](https://github.com/AprilSylph/XKit-Rewritten/actions/runs/9087008669) generated an empty file.

Actions: Print release notes in code block 

---

src/scripts/mass_privater.css
src/scripts/postblock/options/index.css
src/scripts/show_originals.css
src/scripts/tag_replacer.css
src/scripts/themed_posts.js

Changes references to the `--accent` CSS variable to reference `--deprecated-accent`, fixing UI colors in Show Originals, Mass Privater, and Tag Replacer, and... possibly fixing something in Themed Posts in some circumstance? (I can't figure out what the code in question actually affects, so I wasn't able to test that part.)
Resolves #1468. Background: https://github.com/AprilSylph/Palettes-for-Tumblr/pull/185#issuecomment-2134525907.
- Enable Show Originals, navigate to a timeline it affects, and confirm that its control element has a highlight on the selected mode and that it is the correct color.
- Enter an invalid tag into Tag Replacer, press next, and confirm that the tag is shown in the correct color.
- Enter an invalid tag into Mass Privater, press next, and confirm that the tag is …

Fix UI accent colors

---

src/scripts/quick_reblog.css

Resolves #1474.
As noted in the linked issue, a change to Tumblr's CSS resulted in the Quick Reblog menu's fonts changing size and weight, since we did not previously specify them.
(Not sure exactly who I'm writing this note for, as the main person who reads these is the one who pointed the information out to me—thanks April—but the change appears to be that `button`, `input`, `textarea`, and `select` elements have `font: inherit`; presumably some or all did not previously and used browser defaults.)
I'm not actually at all certain that this actually does restore the appearance the menu had prior to both changes, with and without Palettes for Tumblr overrides/XKit 7 Old Blue, in both Firefox and Chromium. I could find one screenshot I had incidentally (Chromium, …

Quick Reblog: Restore changed popup font size/weight

---

src/scripts/accesskit/disable_animations.js

I'd swear I did this already, like, months or years ago.
Gets rid of the fire atop the screen, here.
Enable AccessKit and "disable layout animations." Click the blaze button at the bottom of a post and confirm that the erroneous fire does not appear.

 AccessKit: Hide frozen blaze fire animation

---

src/scripts/quick_tags.js
src/scripts/trim_reblogs.js

As per the linked issue, we can't rely on the translate utility to target DOM elements with CSS/query selectors, as there may be more than one localized string and some may not match the utility's output.
I think this should work? The edit button is always an icon, i.e. not "Edit," right?
Resolves #1459, but the pattern applies more broadly across the extension and another issue should track ensuring they're all made consistent.
- Ensure that Quick Tags and Trim Reblogs buttons are consistently added to editable posts (including in Russian and Hindi; language should not matter now).

 Quick Tags/Trim Reblogs: Fix buttons in Russian and Hindi

---

src/features/postblock/options/index.css

So I'm stupid, and #1471 was a little overzealous.
- Block any post with postblock.
- Confirm that, in the popup UI, the "unblock" button is highlighted in the accent color, as intended.

Postblock: Fix missing accent color in UI

---

src/action/render_scripts.js
src/content_scripts/main.js
src/utils/inject.js

Weirdly, in Safari desktop 17.4.1 (19618.1.15.11.14), if you destructure `const { getURL } = browser.runtime;` the getURL variable will contain a version of the function that _can_ be executed, but returns `undefined` for every string value I tested.
I don't actually know if this a bug or an execution detail per se. Probably a bug? When I log `browser.runtime` I see:
So it seems like, in Safari's implementation, getURL() is not a direct property of `runtime`. I assume this isn't fundamentally the issue—you can destructure inherited methods, right? I never played with this—but, I dunno, maybe some runtime binding is missing, whatever, this is not my area of expertise. Also this is technically through browser-polyfill but I think the result was the same when I tried `const { getURL } = …

Safari compatibility: remove `browser.runtime` destructure

---

src/features/quick_reblog.js
src/features/trim_reblogs.js
src/utils/sidebar.js

We may now use Array.prototype.at due to the browser version requirement bumps in #1466.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at
I confirmed that both avatars and sidebar item insertion in the mobile layout drawer still work (Chrome 126).

Refactor: Use Array.prototype.at

---

src/content_scripts/main.js
src/main_world/index.js

#1514 relies on the fact that fetching a json file and performing an extension storage query will take longer than the browser fetching the main_world script file, as we need the latter to be performed before importing modules with side effects or executing code that uses injection.
This performs a back-and-forth handshake to confirm that the main_world script file has been executed before proceeding with main install.
Random aside: to improve extension load speed slightly, one can do:
```css
const [
installedScripts,
{ enabledScripts = [] }
] = await Promise.all([
getInstalledScripts(),
browser.storage.local.get('enabledScripts'),
mainWorldReady
]);
```
but I can't figure out how to make the code not look stupid.
- Confirm basic extension functionality.
- If desired, unrevert the test …

Main world injection: Prevent race condition

---

src/utils/timeline_id.js

Oops—I had left this on my to-do list, I guess.
This tightens up the `data-timeline-id` processing code by ensuring the search regex can't match a substring of the id attribute in certain cases.
Confirm basic functionality of Show Originals and Collapsed Queue.

Timeline ID util: Enforce exact matches

---

src/utils/timeline_id.js

Adds the current Tumblr Patio timeline IDs to the timeline ID utility, so that we don't need to add them later if they are released in their current state.
The uuid v4 regex is fairly specific, so I can't imagine this will have any side effects.

Timeline ID util: Process current Tumblr Patio IDs

---

src/features/tag_tracking_plus.css
src/features/tag_tracking_plus.js
src/features/tag_tracking_plus.json

Alternative to #1325.
Removes the search dropdown mode and mode selection in Tag Tracking+ due to changes to the search dropdown UI ("improved search typeahead" in Tumblr's code) making it impractical. The sidebar element is now the only mode.

 Tag Tracking+: Remove search dropdown mode

---

src/main_world/index.js

As noted in https://github.com/AprilSylph/XKit-Rewritten/pull/1466#discussion_r1616413489 and previously addressed by #1501, it is possible for exceptions to be logged to the javascript console when we call certain injected functions on a target element that is no longer in the page by the time the injected function is executed.
As of #1514, it is usually fairly difficult for this to happen.
Nevertheless, it should be possible; the first time an injected function is executed it has to be imported asynchronously, for example.
This therefore uses a similar "just don't trigger the listener and resolve the promise" method to prevent any processing code from being run in this now-extremely-rare case. Fortunately, the new structure makes this a oneliner.
- Confirm basic functionality.
If one …

Inject util: Stop processing disconnected elements

---

src/content_scripts/main.js
src/main_world/index.js

Ah, fuck, yeah, it was my fault. I essentially already knew this, too.
If the script element created in initMainWorld is a module script, disabling and re-enabling the extension adds another identical module script to the page. This won't execute anything, because modules are only executed once, and so the whole extension will break on that page.
This changes the main world script (back) to a classic script, fixing this.
See #1550; probably fixes the main issue there, but I haven't fully tested that yet.
In Firefox, turn the extension off and then back on. Without this PR, observe that everything breaks. With this PR, smoke test the extension and confirm it works.

Fix extension restarts in Firefox

---

src/features/quick_reblog.css
src/features/quick_reblog.js
src/features/quick_tags.css
src/features/quick_tags.js
src/utils/interface.js

Right now, it's possible for Quick Tags/Quick Reblog popups to extend past the left or right of their post elements (fundamentally fine) and be clipped off by the edge of the viewport or post column (not fine) in various circumstances. This fixes this by:
- Removing the special "popup is on the left of the button" position entirely.
- Adding logic that finds the closest ancestor element to the popup which would horizontally clip content, whatever it is, and shifts the popup's horizontal position to the left if necessary to keep the popup within that element's bounding box. _(not implemented: shifting it right if it's too far to the left)_
A simpler option, of course, would be to keep the popup horizontally within the post (`const preventOverflowTarget = target.closest(postSelector)`). …

Quick Tags, Quick Reblog: Fix popup horizontal cutoff

---

src/features/collapsed_queue.css

Removes some CSS from Collapsed Queue that a) that were designed for a previous version of the Tumblr UI and no longer make sense to apply and b) were applied even if the feature was turned off on the queue page, which is of course erroneous.
Resolves #1502.
(One of these rules, reducing the height above the footer from 25px to 5px, does look noticeably better to me, but implementing that properly only when the post is actually collapsed would require actual effort to implement and test. Also, not really related to collapsing at all.)
- Confirm that Collapsed Queue still looks fine on the queue page.

Collapsed Queue: Remove outdated erroneous CSS

---

src/features/seen_posts.js

Resolves #1539. Method:
- Detect, via a hopefully-very-specific CSS selector, the addition of an element that only gets added when the user manually soft refreshes a V2 timeline (by using pull to refresh, clicking the tumblr logo, home button, or top of a patio column—are there other ways to trigger this?)
- For each post in a refreshed timeline, if we've already seen it, dim it.
This should be identical in effect to the code in `dimPosts` that is specifically run when `isFirstRender === true`, since that's what we're trying to simulate in this special case. Perhaps we could refactor both to make this slightly more obvious:
```js
// dimPosts
if (seenPosts.includes(id) === false) {
observer.observe(postElement.querySelector('article header + *'));
}
if (isFirstRender && …
```

Seen Posts: Fix soft refresh

---

src/features/tag_tracking_plus.js

Now that `onlyShowNew` is simpler, this copies the `onStorageChanged` code structure from Seen Posts to Tag Tracking+, no longer calling `getPreferences`  in the middle of it. Not important at all; I was just copying it for something else and went, "wait, what is this doing."

Tag Tracking+: minor `onStorageChanged` refactor

---

src/features/quote_replies.js

Threaded replies have a different `type` value internally, so Quote Replies currently doesn't recognize them. This fixes this and adds the correct message to correspond with the activity item text.
~~I didn't bother to file an issue for this, so this doesn't resolve one.~~
- Use Quote Replies on all three types of activity and confirm that it works and the resulting post text matches the activity item text.

Quote Replies: Fix feature on threaded replies

---

src/utils/sidebar.js

Right now, the xkit sidebar is erroneously inserted in between two of the menu items on the right side of the communities settings page. We don't really need it to be on that page at all, similar to how we don't add it to the main Tumblr settings interface, so this prevents this.
- Confirm there is no XKit sidebar on `https://www.tumblr.com/communities/[some community id you have admin in]/settings`. Or, you know, don't; this one's pretty simple.

Sidebar util: Prevent erroneous sidebar in communities settings

---

src/features/tweaks/subtle_activity_mutuals.js

For whatever reason, in the Communities members page, the following/mutuals labels don't have an icon, so the tweak to hide the text and only display the icon makes a pretty silly resulting appearance. This enables the tweak only if there is an icon to show.
- Confirm labels are not affected on (e.g.) https://www.tumblr.com/communities/communities-feedback/members?page=1
- Confirm labels are affected on the activity page

Tweaks: Fix subtle following/mutuals tweak in communities

---

src/features/quote_replies.js

Currently, Quote Replies puts an action button on activity items from communities, but the API request to get the note data 404s, and in general the feature is a little iffy on communities posts even in theory (particularly if we make it create reblogs).
This makes the broken button not appear.

Quote Replies: Don't break on communities activity

---

src/features/cleanfeed.json

The new terminology for Tumblr's content labels is "content label;" this simply adds said term to CleanFeed's searchable metadata.

Cleanfeed: Add "content label" to metadata

---

src/features/notificationblock.js

Enables notificationblock on community posts you authored.
See #1441.
At time of writing, I have a spare community with invite link https://www.tumblr.com/join/oki7cQsr.
- Make an original post in a community.
- Reply to the post.
- Confirm that the post's meatballs menu has a notificationblock button.
- Confirm that notificationblock hides the notification for the reply when it's used.
- Confirm that the post's meatballs menu has a notificationblock unblock button.
- Confirm that notificationblock no longer hides the notification for the reply when it's used.
--
- Reblog a post into a community.
- Reply to the post.
- Confirm that the post's meatballs menu has a notificationblock button.
- Confirm that notificationblock hides the notification for the reply when it's used.
- Confirm that …

NotificationBlock: Enable in communities

---

src/features/tweaks.json
src/features/tweaks/hide_communities_notification_badge.js

Copies the activity notification badge hide tweak for the communities badge.
Leaves, of course, the notification badge on each community when you click to view them all. (Maybe someone wants those hidden too, but that feels like a separate feature. This one is, I imagine/have seen, wanted by a ton of people, me included.)
- Join a community. Wait until there's new activity in it.
- Confirm that the new tweak hides the badge in desktop/tablet/mobile layouts.
- Confirm that this still works in every Tumblr UI language.

Tweaks: Add communities badge hide tweak

---

src/features/show_originals.js
src/utils/react_props.js
src/utils/timeline_id.js

What it says on the tin: this enables Show Originals on the main feeds of Tumblr Communities and the main "community posts" feed.
It also includes a fix for the `isMyPost` utility to detect posts made in communities using a user's sideblog, but that's currently untested since you can't do so yet.
Resolves #1581.
- Confirm that Show Originals works on the main feed of a community.
- Confirm that Show Originals works on https://www.tumblr.com/communities

Show Originals: Enable in communities

---

src/features/quick_reblog.css
src/features/quick_reblog.js
src/utils/user.js

Adds communities the user has joined to the Quick Reblog blog selector dropdown.
Note that posts drafted or queued into a community (presumably) disappear into the ether, so this puts up an error modal if the user tries to do so. (Ideally it should probably grey out the buttons in question; I was hoping one could css select based on a `<select>`'s current value but I'm not sure you can, so this would probably have to be a bunch of js.)
Should alreadyReblogged exclude reblogging into a community? ¯\\\_(ツ)\_/¯ 
At time of writing, I have a spare community with invite link [tumblr.com/join/oki7cQsr](https://www.tumblr.com/join/oki7cQsr).
todo: list performed tests

Quick Reblog: Enable reblogging posts into communities

---

src/features/no_recommended/hide_recommended_posts.js

Back in #1008 I added "Too many recommended posts to hide!" fallback code when No Recommended hid way too many posts in a row. In #1213, I apparently made a typo and completely broke it, which we (quite reasonably, imho) didn't notice.
This fixes it... mostly. There are some edge cases, but it's good enough, I think.
Notably, the virtual scroller means that some cell elements are empty and thus won't match `postSelector` even though they are actually posts.
This one might be best to treat as a "just look at the diff," honestly? Or, more accurately, "hey, can't be worse than it was before." But I committed the code I was using with a bunch of random logging and a simulation of having a lot more recommended posts.

No Recommended: Fix fallback behavior when hiding the entire dash

---

src/utils/user.js

This takes around 100ms off the extension's initial load speed by performing both fetches in the user util at once.
- Confirm basic extension functionality.
- Modify the communities API URL so that it's incorrect and its fetch will fail. Confirm that Quick Reblog does not have communities as reblog targets, but that the extension continues to function otherwise.

User util: Improve extension load speed

---

src/content_scripts/main.js
src/main_world/index.js
src/utils/inject.js

Resolves  #1597. See issue for background.
A fairly elegant, self-contained way to prevent this problem is to remove the previous version of the event listener. Fortunately, javascript supplies us with a way to do this: the `AbortController`. This is compatible with #1538, as it requires no communication between the main world script(s) and content script.
This won't apply to the instance where a version of the code without this PR merged is replaced by one with it, so this also changes the custom event names to handle that case.
- Load the extension in Firefox.
- Turn the extension on and off a large number of times.
- Reblog a post with Quick Reblog and confirm that it is only reblogged once.

Fix Quick Reblog double reblogs after extension update/restart (alternative 4)

---

src/features/tweaks/hide_following_notification_badge.js

> I thought I remember instances in which the React code modified the title element rather than replacing it (and why wouldn't it, after all, if that's the minimal DOM diff). That being said...
_Originally posted by @marcustyphoon in https://github.com/AprilSylph/XKit-Rewritten/issues/1360#issuecomment-1922832314_
Yeah, I don't know why I ever believed we wouldn't have to handle that case.
When navigating from one tagged page to another, with our "Hide the Home/Following unread count" tweak enabled, the page title is not updated due to limitations in the code that detects the page title changing.
This fixes this by observing changes to the title element as well as its replacement, as my original code did.
Resolves #1613.
- Enable the "Hide the Home/Following unread count" tweak
- Navigate …

Fix page title not being updated when navigating

---

src/utils/meatballs.js

Fixes an obvious typo in my blog-meatball-menu-item code that prevents the removal of outdated items.
Resolves #1140.
Not tested (we don't currently have a script that uses this part of the util). Could be tested by merging the Mute PR, opening a blog meatball menu, changing a Mute setting with it open, and confirming that the menu item is no longer duplicated when the feature restarts.

Meatballs util: Fix blog meatball items not being removed

---

src/features/tweaks/hide_activity_notification_badge.js
src/features/tweaks/hide_communities_notification_badge.js
src/features/tweaks/hide_following_notification_badge.js

This improves the badge-hiding tweaks by:
- removing reliance on translation strings that have multiple possible translation values in selectors (checked via https://gist.github.com/marcustyphoon/5cffac5d1c480603696e777632943f3a), ensuring they work in all UI languages
- adding `li` to selectors missing them, an oversight that made them not apply to the mobile menu
- adding an alternative href attribute used for the old (pre-vertical-nav) dashboard, in case anyone is still running that
Resolves  #1461.
Confirm that the notification badge hiding tweaks work:
- in all page widths of the regular desktop layout
- in the mobile layout menu tray

Tweaks: Improve badge hiding tweak reliability

---

src/utils/timeline_id.js

Community feeds ~will soon be~ _are_ able to be added to Patio as columns; this adds the relevant timeline ID format.
Add a community column to Tumblr Patio ~via Methods™~. Confirm that Show Originals works on it now.

Timeline ID util: Add community patio column ID

---

src/features/no_recommended.json
src/features/no_recommended/hide_community_carousels.js

~~Not currently tested; I've never seen one of these and extrapolated the format by looking at the code.~~
Adds an option to No Recommended to hide the recommended community carousels on the For You page.

No Recommended: Hide recommended communities feature

---

src/features/tweaks/highlight_contributed_content.js

As noted in the linked issue, the "highlight contributed content" tweak looks like it applies a subtle color highlight to the relevant trail item, but it's actually overriding the background with the `follow` palette color, which generally has that effect on most palettes but isn't compatible with customization.
This applies a low-opacity accent color instead. 7% matches more closely with the current color on the True Blue palette, but I like ~10% better in general.
I also tried `blue` instead of `accent`.
> I prefer blue on:
> cement, strongly
> 
> I prefer deprecated-accent on:
> vampire, moderately
> goth rave, slightly
Most notably, though we override `accent` in Themed Posts, but we don't override `blue`, so `accent` gives more stable results.
In addition, this disables the tweak's …

Tweaks: Improve contributed content tweak compatibility

---

src/features/collapsed_queue.js

As mentioned in the comments of #1529, if one opens a draft in the post editor and then closes it (whether or not they save the edit), the post gets rerendered and this removes Collapsed Queue's DOM modifications. This fixes this.
We should probably do another pass on `excludeClass` use at some point, I suppose.
- Enable Collapsed Queue on drafts
- Click edit on a draft
- Exit the editor
- Confirm that the draft is still collapsed

Collapsed Queue: Fix uncollapsing when posts are edited

---

src/utils/user.js

This adjusts the order of the user's communities (i.e. in Quick Reblog) to match the order the user has chosen in the sidebar. Tumblr saves this on a per-browser basis. (If it's in the roadmap to move this ordering to the server soon, this of course makes little sense to merge.)
Really feels like `indexOf` would default to undefined instead of -1 if implemented today, don't you think?
- Join multiple communities.
- Confirm that Quick Reblog lists communities in the same order in which they appear in the Tumblr sidebar.
- Change the order of the communities in the Tumblr sidebar.
- Refresh the page.
- Confirm that Quick Reblog lists communities in the same order in which they appear in the Tumblr sidebar.
<br />
- Edit an error into the JSON.parse block. Confirm that Quick Reblog still …

Quick Reblog: Respect user community sort order

---

src/features/vanilla_video.js

As noted in the linked issue, when running Vanilla Video with endless scrolling enabled it's possible for posts to overlap each other in certain circumstances. I never truly figured out what sequence of events occurs here, but there must be a time at which the Tumblr code reads the height of a post element containing a video, gets that the video is too short (the default vertical height of a video element), uses that to place the next post, and doesn't update this once the video poster and/or source load in and change the video element height.
This solves this by setting the aspect ratio of the Vanilla Videos video element before inserting it, ensuring that there's no way for its height to ever be rendered as another value.
In theory, we could probably add an onload function that removes …

Vanilla Video: Fix possible post overlap

---

src/features/mass_privater.js

Resolves #1609.
This changes the "checked x" count that Mass Privater shows while fetching posts to include all posts without any filtering, ensuring that it continues to increment in real time even if the posts currently being fetched aren't relevant.
This includes counting the same post multiple times if it has multiple searched tags and gets fetched multiple times; do you think this makes sense? (Maybe it makes "checked x" slightly inaccurate; that could be "fetched x" or "downloaded x" something, I dunno.) There's a tradeoff here.
I did not really test this, as I don't have enough private posts to notice the difference.

Mass Privater: Display total fetched count without filtering

---

package-lock.json

Due to https://github.com/npm/cli/issues/4608, a "name" property was added to the package-lock.json file by `npm audit fix` in 01fe042bac00fb5c6d1a3f0a4abd9c1ab45c6fe3 even though `npm install` removes it again.
This commits the diff caused by running `npm install`. Of course, if the linked issue gets resolved in the other direction (always creating a name property in package-lock.json based on the folder name if there is no name in package.json), this would be incorrect, but this is how it is at the moment. (Also, that wouldn't make much sense as a resolution, imho).
n/a

chore(deps): remove package-lock.json name property

---

src/features/scroll_to_bottom.js
src/utils/meatballs.js

This standardizes the capitalization of "onclick" to all-lowercase.
For some reason—I think a misguided notion that it was correct and the opposite was a mistake—I used "onClick" in #910, even though it's "onclick" in the utilities exported from the same file. This isn't used in any current feature, but it is used in #677, so that PR must be updated after merging this one.

Refactor: Standardize capitalization of "onclick"

---

src/features/quick_reblog.js

Quick Reblog currently:
- Logs a mysterious-looking error to the console if and only if the user is logged out or the user info api fetch fails and the "Remember the last selected blog in the popup" option is enabled.
- Works, but only shows communities as reblog targets, if and only if the user info api fetch fails, the communities info api fetch doesn't fail, **and** the "Remember the last selected blog in the popup" option is disabled.
None of this really makes any sense as error-handling behavior. This PR makes the extension exit cleanly (though we could add a log here) if there is no user info, thus making it so that Quick Reblog:
- Does nothing if the user is logged out.
- Does nothing if the user info api fetch fails.
- Never only shows communities as reblog targets.
- Works, but …

Quick Reblog: Exit cleanly without user info

---

src/features/accesskit/visible_alt_text.js

Simple enough.
This skips processing image elements with `alt` attributes that are actually empty strings, treating them the same way we do images without the attribute at all. This fixes empty caption elements being added below GIFs without alt text.
Resolves #1687.
- Confirm that GIFs in posts that don't have alt text (try https://www.tumblr.com/search/gif) aren't affected by AccessKit Visible Alt Text.
- Confirm that images with alt text (try https://www.tumblr.com/search/described) are still affected by AccessKit Visible Alt Text.
- Confirm that GIFs with alt text (try https://www.tumblr.com/meltknuckles/757727655146799104/a-herd-of-dairy-cow-isopods-grazing-the-great) are still affected by AccessKit Visible Alt Text.

AccessKit Visible Alt Text: Fix empty captions on GIFs without alt text

---

src/features/tag_tracking_plus.js

The minimum change required to fix #1666. This skips attempting to process post elements that have already been removed from the page in the count clearing check in Tag Tracking+.
Confirm general feature functionality.

Tag Tracking+: Improve count clearing consistency

---

src/features/tweaks/hide_activity_mutuals.js

As noted in #1658, there is a tweaked Tumblr notification type which breaks some features, like the "hide following/mutuals indicators on notifications" tweak. This fixes this one.
Resolves #1692.
- Confirm that the feature functions correctly on a new "replied to your post"/"replied to you in a post" notification from a mutual/followed user on both the activity page and in the activity modal.
- Confirm that the feature functions correctly on the classic style of notification (most other notification types) from a mutual/followed user on both the activity page and in the activity modal.
- Confirm that the mutual/following indicators on the communities members page are unaffected.

Tweaks: Fix "hide following/mutuals indicators on notifications" option

---

src/features/tweaks/hide_communities_notification_badge.js

Updates the communities button selector in the "Hide the Communities notification badge" tweak, restoring its functionality.
Resolves #1690.
Confirm that the tweak in question functions in each browser viewport width, including in the mobile drawer.

Tweaks: Fix "Hide the Communities notification badge" tweak

---

src/features/tweaks/hide_mini_follow.js

Per the linked issue, this excludes a special follow button on blazed posts from the selector used in the "hide mini-follow buttons on posts" tweak.
Thankfully, I got another blazed post to test this pretty quickly.
Resolves #1697.
- Confirm that normal posts have their mini follow buttons hidden by the tweak.
- Find a blazed post and confirm that its pill-shaped follow button is unaffected by the tweak.

Tweaks: Fix blazed posts UI with "Hide mini follow button" tweak

---

src/features/no_recommended.json
src/features/no_recommended/hide_search_communities.js

Adds a No Recommended feature to hide the "suggested communities" section in the search dropdown ("typeahead", but even I, an ostensible web developer, have no idea what that is).
I was considering instead making a tweak that puts the suggested communities at the bottom of the search dropdown, but thinking about it, no: this is totally internally consistent with the rest of the extension. We don't hide parts of the UI with unique functions or ways to navigate to them; we do hide parts of the UI whose sole purpose is to give algorithmic recommendations, and the place to do that is in No Recommended.
I have checked that "Suggested communities" currently only has one translation by downloading the raw language data.
- Enable the new No Recommended checkbox and confirm that the "suggested …

No Recommended: Hide communities in the search dropdown

---

src/features/mutual_checker.js

It appears that it doesn't need to be any more complex than this!
Applies Mutual Checker to the timestamps in the new unique post header used in tumblr communities (`communitiesRedpopPostChrome`) by taking advantage of the `rel="author"` property. I see no reason why additional elements would be added with this property and I assume(?) it's fine to rely on the property not being forgotten/lost in the future?
Resolves #1694.
- Confirm that Mutual Checker works on community posts with the new header (feature flag enabled).
- Confirm that Mutual Checker works on non-community posts.
I'd like to find a blazed-by-someone-else post to see what happens here (semi-related: #1069) but that's quite unlikely so I may have to just read the code. But, like... eh, who cares, also.

Mutual Checker: Apply to new communities post header

---

src/features/no_recommended/hide_blog_carousels.js
src/features/no_recommended/hide_community_carousels.js

This fixes the "Hide recommended communities between posts" and "Hide recommended blogs between posts" features of No Recommended when certain other extension features are enabled, such as Tumblr Savior's "Hide timeline objects" setting, and endless scrolling is enabled.
It may improve the reliability of both features with endless scrolling in general.
Resolves #1724.
As noted in the linked issue, Tumblr's virtual scroller may remove the "titleObject" element from the DOM before our code processes the carousel element. We thus need to not rely on its presence.
These features are a pain to test because the elements they hide don't always show up and will show up less if you repeatedly view a timeline they're allowed to appear on. The For You tab seems to have some carousels a bit more …

No Recommended: Fix blog/community hiding with Tumblr Savior enabled

---

src/utils/meatballs.js

This cleans up a big chunk of copy-pasted code that was added to the meatballs util in #910, making the addition of meatball menu items generic over different types (post, blog). This makes it easier to add additional types of meatball menu to target (#1662).
- Confirm that PostBlock/Mirror Posts meatball items work correctly.
- Confirm that NotificationBlock meatball items only appear on user posts and work correctly.
- Merge #677 into this PR and confirm that blog meatball items work correctly.

Meatballs util: Refactor; remove duplicate code

---

src/utils/memoize.js
src/utils/react_props.js

This creates and uses helpers for creating memoized (cached) versions of functions with a single argument by creating a closure, similar to the way that `debounce` creates debounced versions of functions. (I found myself writing another one of these for a different PR and went, wait, hold on, why have we not just done this).
Bikesheddable: this makes a util file with two exports, one of which uses a WeakMap; it could alternatively be a single export that takes an additional config argument of some kind along with the target function. I don't think that reads as elegantly when used, though.
Smoke test the extension; I haven't done specific tests to verify that the caching still works.

Extract memoize helper function

---

src/features/tweaks/restore_attribution_links.js

This updates the selectors in the "restore links to individual posts" tweak so the feature will apply to the new post header that's used in community posts if it's ever used for regular ones.
I can confirm that this works with unreleased code, but it isn't really currently testable normally.
- Confirm that the "restore links to individual posts" tweak affects post attribution and reblog attribution links on "regular" posts.

Tweaks: Apply "restore links to individual posts" to new post header

---

src/features/timeformat.js

Applies timeformat to the timestamps in the new unique post header used in tumblr communities (`communitiesRedpopPostChrome`).
~~Not sure if this will break anything else, like mutual checker~~ yes it does.
Is this actually... desirable? I mean, I assume so, though the aesthetics aren't great.
- Confirm that Timeformat works on community posts with the new header (feature flag enabled).

Timeformat: Apply to new communities post header

---

src/features/vanilla_video.js

Vanilla Videos currently creates video elements with the incorrect height when a source video has non-square pixels. This fixes this by removing the (usually correct, but sometimes erroneous) aspect ratio override that causes the issue once it's no longer needed to prevent virtual scroller bugs.
I actually kind of predicted that this would be necessary in #1652, which added the code in question:
> In theory, we could probably add an onload function that removes the CSS property this adds, ensuring that if for some reason the width/height values set on the video element by redpop differ from the actual resulting video's size they'll be ignored.
I admittedly didn't do much research into the events we could use here. `loadedmetadata` seemed to work, so...
- With this PR, enable Vanilla …

Vanilla Videos: Fix non square pixel video aspect ratio

---

src/features/accesskit/disable_gifs.js

At present, AccessKit does pause GIFs in recommended blog carousels, but they don't unpause on hover. This makes the recommended blog cards into hover-to-unpause targets.
<details><summary>outdated; see comment below</summary>
At present, AccessKit does pause GIFs in recommended blog carousels, but a) they don't unpause on hover, and b) there are sometimes two overlapping gif labels visible due to the way Tumblr makes a blurred background copy of non-square images*. This ~hides~ _removes_ the duplicate labels and makes the recommended blog cards into hover-to-unpause targets.
*~~I can't get a screenshot of this because by the time I reverted this PR, I no longer had any of these. Developing modifications for a nondeterministic feature is annoying.~~ **edit:** …

AccessKit Disable GIFs: Fix recommended blog card hover

---

src/features/accesskit.json
src/features/tweaks.json

> Side note, we need to update our verbiage from "Changes/Shop/etc. links carousel" in AccessKit and Tweaks... there's no more Tumblr shop link in that carousel.
_Originally posted by @AprilSylph in https://github.com/AprilSylph/XKit-Rewritten/discussions/1745#discussioncomment-12582154_
Confirm that the changes to labels look reasonable in the options UI.

chore: Rename Changes/Shop/etc. carousel in options UI

---

src/utils/modals.js

Just as in https://github.com/new-xkit/XKit/pull/2101, this fixes an issue where Tumblr's code would steal focus from and break form input elements in our modal overlay UI because it was trying to prioritize its own. In this case, it was when something like Tag Replacer or Mass Deleter/Privater/Unliker was opened from the sidebar menu where they are in mobile device/tablet viewport widths.
Resolves #1759.
Thanks to Gideon on the New XKit discord for reporting this!
- Confirm that Tag Replacer/Mass [whatever] features work in <990px and <540px viewport widths.

fix: Modal UI broken in mobile/tablet browser widths

---

src/features/no_recommended.json
src/features/no_recommended/hide_recommended_community_posts.js

This adds a No Recommended option that hides posts from non-followed communities in the For You feed, something which Tumblr doesn't have a config option for. Many users find that this type of recommendation, at least at the moment, often isn't relevant to their interests. (Maybe that'll change with increased use of communities, but at least in my experience there simply doesn't seem to be enough communities content for pretty much any of it to be relevant to me.)
Note that Tumblr _does_ have an option not to add posts from communities you **do** follow in the **Following** feed; it's near the bottom of https://www.tumblr.com/settings/dashboard. We naturally won't add an XKit option to do this, as that would be redundant.
- Confirm that the new No Recommended option works as specified on …

No Recommended: Hide posts from non-joined communities in For You

---

src/features/accesskit/disable_gifs.js

This prevents AccessKit Disable GIFs from processing blog avatar elements in posts, preventing "GIF" labels from being added to avatars that aren't animated, but have the GIF filetype.
This being a good idea is based on the assumption that Tumblr successfully prevents users from uploading animated avatar images. (Of course, if that fails we'd want to add a bunch of CSS selectors to _consistently_ pause avatar images; right now only the new header element used in communities is affected.)
- Enable AccessKit Disable GIFs and confirm that the blog avatar in https://www.tumblr.com/communities/test-community-46174/post/778120974205878272/post-from-a-blog-with-a-gif-avatar does not have a Disable GIFs label.

AccessKit Disable GIFs: Exclude blog avatars

---

src/features/tweaks/hide_footer_tooltips.js

This fixes the "hide footer tooltips" tweak on accounts with the new split-notes post footer.
- Confirm that the tweak hides tooltips on all footer variations.

Tweaks: Fix "hide control button tooltips" tweak in split-notes footer

---

src/features/quick_reblog.css
src/features/quick_reblog.js

This fixes Quick Reblog on accounts with the new split-notes post footer.
Edit: There are actually two footer variations in testing, so this should address both!
On all three footer variations:
- Confirm that the Quick Reblog popup appears, in the correct location, when hovering over the reblog button.
- Confirm that the Quick Reblog popup is not covered by Tumblr's control button tooltip, as the tooltip is now hidden by this feature.
- Confirm that alreadyreblogged posts have different-colored reblog icons.
Note: I haven't done a full round of testing on this after my last few changes, unless I've crossed out this line in the description.

Quick Reblog: Fix feature on accounts with new footer variants

---

src/content_scripts/control_buttons.css
src/features/quick_tags.js
src/features/trim_reblogs.js
src/utils/control_buttons.js

This is a way to fix Quick Tags and Trim Reblogs, the features that add control buttons to posts, on accounts with the two new post footer variants. Control buttons are added in an additional secondary row above the footer control buttons, as in the current footer layout, which must be added by a new util function.
If we use this method, we should make sure that this code is easy to copy into and can be compatible with XKit 7 in case we ever get around to performing the same fix on it.
Note that this CSS might be a little imprecise (for example, I split the difference between some mobile/non-mobile spacing values, iirc; I was in a bit of rush to get an MVP out). We're not directly reproducing a layout that exists; feel free to weigh in.
On all footer variations:
- Confirm that Quick …

Quick Tags, Trim Reblogs: Fix features on accounts with new footer variants

---

src/features/shorten_posts.css

This prevents the UI elements added at the bottom of a Shorten Posts shortened post from covering the dashboard tab bar and search interface atop search pages when scrolled to a position in which one overlaps the other.
Resolves #1400.
- Confirm that the dashboard tab bar appears on top of the Shorten Posts expand button.
- Confirm that the dashboard tab bar appears on top of the Shorten Posts tags element.
- Confirm that the "top/latest/etc" selector atop a search page in the desktop layout appears on top of the Shorten Posts expand button.
- Confirm that the "top/latest/etc" selector atop a search page in the desktop layout appears on top of the Shorten Posts tags element.
- Confirm that the search bar atop a search page in the tablet layout appears on top of the Shorten Posts expand …

Shorten Posts: Fix button/tags covering tab bar and search box/dropdown

---

src/features/mutual_checker.js

This removes the April Fools' joke from Mutual Checker until we come up with something else.
Confirm that Mutual Checker icons are still added to posts.

Mutual Checker: Remove old April Fools' joke

---

src/features/timeformat.js

This fixes the layout improvements added in #1110 and an erroneous lack of underline beneath the relative part of the formatted time when hovered in reply timestamps that are links (currently unreleased/in-testing Tumblr code).
- Enable the "append relative time" option in TimeFormat and find a reply with a relatively long blog name (such as <https://www.tumblr.com/once-more-with-gravitas/778774885212225536/ah-dangit>).
- Confirm that reply timestamps stay as a single line with and without the relevant feature flag.
- Confirm that reply timestamps are underlined consistently when hovered with the relevant feature flag.

TimeFormat: Fix reply timestamp formatting

---

src/features/anti_capitalism.js
src/features/anti_capitalism.json

Blazed posts are somewhat different than third-party algorithmic advertising, and some users of this feature might want to continue to see them. ~~I'm not actually sure if they still show up with e.g. ublock origin lite enabled (it was hard enough just finding a blazed post to test this on at all), but it's not like one has to do that.~~ **edit:** _ah, managed to get one in testing and they do! nice._
Note that this doesn't apply to the kind of advertisement that appears sort of like a post with a large CTA button at the bottom (not sure if this is what Blaze Pro is). I get these from Tor Books; they do have post ids but do not have the orange blaze icon anywhere.
- Find a blazed post on the dashboard. Enable Anti-Capitalism and confirm that the post is hidden only when the checkbox is …

Anti-Capitalism: Make blazed post hiding optional

---

eslint.config.js

Re-enables `import/recommended` (now actually `import-x/recommended`) (actually not that either because the format for reusable eslint configs is completely different now) lint rules that were previously removed in #1815.
I was a little too trusting of `neostandard`'s rules. Turns out, it doesn't even enable the `no-unresolved` lint rule, which I found to be kind of important for implementing the new directory structure for `src/features/`, as discussed in #1816.
Code review and green CI is enough.

chore: (re-)enable `import-x` recommended lint rules

---

src/action/render_features.js
src/content_scripts/main.js

#1828:
> This PR intentionally does not update the `"enabledScripts"` storage key or any of its usages, since this PR is already rather big, and by its nature of doing mass-renaming should be tested thoroughly; adding any migratory code for `"enabledScripts"` &rarr; `"enabledFeatures"` would fall outside the scope of this testing.
This PR does not update the `"enabledScripts"` storage key, but **does** update its usages by making the key a variable.
Feel free to point this at master or at #1828, or to just pull the diff as part of actually updating the storage key and discarding this, whichever you prefer!
See testing steps for #1828.

chore: rename "enabledScripts" to "enabledFeatures" in internal code

---

src/features/quick_reblog/index.css
src/features/quick_reblog/index.js

On accounts without footer changes, the reblog icon in the mode selector in the notes view was colored green if the user has reblogged the post with quick reblog, etc. This makes sure the coloration is only applied to the correct button.
Not sure if there is a more elegant way to do this.
Resolves #1845.
On all 3 footer variations:
- Confirm that the reblog button changes color when Quick Reblog is used to reblog a post.
- Confirm that nothing in the notes view changes color when Quick Reblog is used to reblog a post.

Quick Reblog: Fix already-reblogged button coloration in notes view

---

src/features/quick_reblog/index.css
src/features/quick_reblog/index.js

- Fixes #1846
Updates Quick Reblog to restore the AlreadyReblogged tick on already-reblogged posts' reblog buttons when the user has one of the two new 2025 post footer variants, via `mask-image` magic that I stole from my past self (the new post header's avatar component uses this to display cut-outs for badges/sub-avatars too).
The magic numbers for how the mask works is... part science, part magic. The first two magic numbers are the ellipsis dimensions, which should match the tick's bounding box dimensions. The positional magic numbers are... kind of just whatever worked? To figure out how to get a perfect overlap, I temporarily added `background-color: red` to the masked SVG element and `background-color: blue` to the tick pseudo-element. Then, I just played with the position until …

fix(Quick Reblog): restore AlreadyReblogged tick in new post footer variants

---

renovate.json

- Relates to #1856
- See [Configuration Options - Renovate Docs § `minimumReleaseAge`](https://docs.renovatebot.com/configuration-options/#minimumreleaseage)
> #### Prevent holding broken npm packages
> npm packages less than 72 hours (3 days) old can be unpublished from the npm registry, which could result in a service impact if you have already updated to it. Set `minimumReleaseAge` to `3 days` for npm packages to prevent relying on a package that can be removed from the registry[.]
1. Pull this branch locally
2. Run `npx --yes --package renovate -- renovate-config-validator`
```
INFO: Validating renovate.json
INFO: Config validated successfully
```

chore: prevent holding broken npm packages

---

src/features/quick_tags/options/index.js

Not sure exactly what this does, but this enables the [forceFallback option in SortableJS](https://github.com/SortableJS/Sortable#forcefallback-option), which may make it more compatible in unusual situations.
Resolves #1858, hopefully.
As in #1749:
- Confirm that tag bundles can be dragged to rearrange them in the options UI and that the drag action rotates the bundle order in the tag popup.
- Confirm that scrolling is not affected negatively on mobile devices.
Not sure how to find the kind of bugs that the linked issue is about besides "try to screw with it a lot."

Quick Tags: Improve drag sort compatibility

---

src/features/accesskit/disable_gifs.js

This adds additional selectors for GIFs that can be paused with minimal changes to the current Disable GIFs code and comments that list the elements referred to.
Based off of the branch for #1853 and tested that way. **Note:** most/all of these don't need that PR; let me know if you'd like them tested and PR'd separately. If merging both, it reduces testing to test them together (though it might require a rebase of this branch, annoyingly).
- Confirm that each element listed in the source code is paused correctly, has a label, and unpauses correctly when hovered.
- Confirm that paused carousels on https://www.tumblr.com/dashboard/trending / https://www.tumblr.com/dashboard/hubs have readable text.
Note: the GIFs in the search dropdown modal don't have labels when I test this in Safari …

AccessKit Disable GIFs: Pause additional elements

---

src/action/backup.css
src/action/popup.html

Fun fact: setting `display: flex` or setting margin on the child of a `details` element in chromium doesn't seem to work. (I see `slot` in chromium devtools; maybe `details` is implemented as a custom element?) Anyway, this results in slightly incorrect spacing in the backup section of the XKit Rewritten menu, and is kind of a pain if you try to add an element to it.
This PR is... I dunno, one way to solve this. There may be better ones. As mentioned a number of times, I consider myself a CSS layout... intermediate, I guess, at best?
Confirm that the backup section of the XKit Rewritten menu has correct-looking layout in both Firefox and Chrome when either/neither element is expanded.

Adjust menu backup section layout for chromium compatibility
